In [1]:
from keras.preprocessing.image import img_to_array
from keras.models import load_model
import numpy as np
import argparse
import imutils
import cv2

Using TensorFlow backend.
/home/autom8-sudesh/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/autom8-sudesh/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/autom8-sudesh/.local/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/autom8-sudesh/.local/lib/python3.6/sit

In [2]:
detector = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
model = load_model('model.hdf5')
EMOTIONS = ['Anger', 'Disgust', 'Fear', 'Happy', 'Sad', 'Surprise', 'Neutral']

Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.


In [3]:
camera = cv2.VideoCapture(0)



In [4]:
while True:
    # grab the current frame
    (grabbed, frame) = camera.read()
    frame = imutils.resize(frame, width=300)
    print(frame)
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    canvas = np.zeros((220, 300, 3), dtype="uint8")
    frameClone = frame.copy()
    rects = detector.detectMultiScale(gray, scaleFactor=1.1,minNeighbors=5, minSize=(30, 30),flags=cv2.CASCADE_SCALE_IMAGE)
    if len(rects) > 0:
        # determine the largest face area
        rect = sorted(rects, reverse=True,
        key=lambda x: (x[2] - x[0]) * (x[3] - x[1]))[0]
        (fX, fY, fW, fH) = rect
        roi = gray[fY:fY + fH, fX:fX + fW]
        roi = cv2.resize(roi, (48, 48))
        roi = roi.astype("float") / 255.0
        roi = img_to_array(roi)
        roi = np.expand_dims(roi, axis=0)
        preds = model.predict(roi)[0]
        label = EMOTIONS[preds.argmax()]
        for (i, (emotion, prob)) in enumerate(zip(EMOTIONS, preds)):
            # construct the label text
            text = "{}: {:.2f}%".format(emotion, prob * 100)
            w = int(prob * 300)
            cv2.rectangle(canvas, (5, (i * 35) + 5),
            (w, (i * 35) + 35), (0, 0, 255), -1)
            cv2.putText(canvas, text, (10, (i * 35) + 23),
            cv2.FONT_HERSHEY_SIMPLEX, 0.45,
            (255, 255, 255), 2)
            
        cv2.putText(frameClone, label, (fX, fY - 10),
        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 0, 255), 2)
        cv2.rectangle(frameClone, (fX, fY), (fX + fW, fY + fH),
        (0, 0, 255), 2)
    cv2.imshow("Face", frameClone)
    cv2.imshow("Probabilities", canvas)
    if cv2.waitKey(1) & 0xFF == ord("q"):
            break
camera.release()
cv2.destroyAllWindows()

[[[207 177 182]
  [203 173 176]
  [199 175 176]
  ...
  [ 54  54  50]
  [ 39  48  45]
  [ 32  40  33]]

 [[198 172 178]
  [198 174 176]
  [199 177 176]
  ...
  [ 46  44  26]
  [ 43  42  32]
  [ 44  40  40]]

 [[203 170 185]
  [203 173 179]
  [207 181 182]
  ...
  [ 44  46  35]
  [ 45  48  41]
  [ 43  45  41]]

 ...

 [[ 74  52  60]
  [ 70  53  64]
  [ 57  54  66]
  ...
  [ 98  85 108]
  [ 90  77 107]
  [ 66  53  88]]

 [[ 70  49  54]
  [ 76  66  70]
  [ 63  65  73]
  ...
  [107 102 109]
  [101 105 112]
  [ 86 101 108]]

 [[ 72  54  79]
  [ 76  67  83]
  [ 57  58  69]
  ...
  [120 123 115]
  [106 114 103]
  [105 118 106]]]
[[[202 177 181]
  [199 170 173]
  [205 174 173]
  ...
  [ 34  58  52]
  [ 38  45  43]
  [ 42  32  33]]

 [[196 180 164]
  [198 180 169]
  [206 182 178]
  ...
  [ 33  54  36]
  [ 44  56  43]
  [ 51  55  47]]

 [[201 175 163]
  [200 175 162]
  [204 178 173]
  ...
  [ 38  50  37]
  [ 42  49  29]
  [ 53  58  34]]

 ...

 [[ 50  60  72]
  [ 56  61  70]
  [ 56  57  61]
  ..

[[[206 182 174]
  [207 176 171]
  [214 174 176]
  ...
  [ 52  41  46]
  [ 63  39  46]
  [ 71  34  39]]

 [[199 186 172]
  [198 177 171]
  [196 174 174]
  ...
  [ 50  46  27]
  [ 60  37  32]
  [ 70  30  36]]

 [[192 176 174]
  [194 175 174]
  [200 183 181]
  ...
  [ 41  47  31]
  [ 50  41  32]
  [ 51  28  25]]

 ...

 [[ 62  54  60]
  [ 52  45  50]
  [ 64  59  65]
  ...
  [ 86  82 105]
  [ 85  75 107]
  [ 72  57  91]]

 [[ 65  49  61]
  [ 67  49  62]
  [ 80  64  73]
  ...
  [ 95  91  98]
  [102  91 104]
  [ 97  80  99]]

 [[ 73  54  67]
  [ 76  57  66]
  [ 75  58  61]
  ...
  [115 116 111]
  [114 108 108]
  [112 102 104]]]
[[[198 179 174]
  [197 175 172]
  [204 182 178]
  ...
  [ 48  37  52]
  [ 52  38  39]
  [ 54  40  31]]

 [[208 178 174]
  [203 171 169]
  [208 174 180]
  ...
  [ 44  48  33]
  [ 41  38  21]
  [ 58  42  27]]

 [[204 174 175]
  [201 171 172]
  [209 181 183]
  ...
  [ 41  46  37]
  [ 41  41  29]
  [ 45  38  27]]

 ...

 [[ 57  65  83]
  [ 57  62  74]
  [ 55  58  70]
  ..

[[[203 186 175]
  [196 182 176]
  [198 185 186]
  ...
  [ 58  39  43]
  [ 51  42  48]
  [ 43  42  53]]

 [[200 183 178]
  [196 180 178]
  [202 182 186]
  ...
  [ 43  36  35]
  [ 53  43  42]
  [ 53  43  45]]

 [[195 176 179]
  [195 175 178]
  [199 177 180]
  ...
  [ 36  42  31]
  [ 47  38  33]
  [ 54  39  37]]

 ...

 [[ 51  63  57]
  [ 51  62  54]
  [ 61  65  62]
  ...
  [ 86  88  97]
  [ 90  90 100]
  [ 69  71  85]]

 [[ 59  57  53]
  [ 60  64  59]
  [ 55  65  62]
  ...
  [104 108 111]
  [ 96 101 102]
  [ 82  86  87]]

 [[ 61  50  64]
  [ 61  64  71]
  [ 49  69  66]
  ...
  [107 116 107]
  [105 119 112]
  [102 116 107]]]
[[[202 184 171]
  [196 175 167]
  [199 175 178]
  ...
  [ 54  41  39]
  [ 45  37  43]
  [ 44  41  56]]

 [[198 181 159]
  [196 179 162]
  [206 185 183]
  ...
  [ 47  43  36]
  [ 50  40  40]
  [ 55  44  51]]

 [[198 176 175]
  [196 175 171]
  [199 180 174]
  ...
  [ 45  46  49]
  [ 50  41  47]
  [ 60  45  51]]

 ...

 [[ 43  61  73]
  [ 53  57  70]
  [ 55  51  63]
  ..

[[[197 181 164]
  [199 183 170]
  [199 176 178]
  ...
  [ 51  35  37]
  [ 50  37  44]
  [ 45  38  46]]

 [[203 183 170]
  [200 178 170]
  [197 178 178]
  ...
  [ 46  54  58]
  [ 38  47  53]
  [ 42  48  53]]

 [[202 168 167]
  [204 176 170]
  [203 182 178]
  ...
  [ 56  50  60]
  [ 56  47  55]
  [ 59  47  52]]

 ...

 [[ 64  62  77]
  [ 57  59  68]
  [ 51  59  62]
  ...
  [130 115 120]
  [127 113 113]
  [123 107 103]]

 [[ 49  62  73]
  [ 50  65  71]
  [ 53  63  74]
  ...
  [134 126 128]
  [130 123 124]
  [128 124 124]]

 [[ 41  65  75]
  [ 46  64  71]
  [ 44  57  61]
  ...
  [137 123 124]
  [116 114 109]
  [119 128 114]]]
[[[215 182 158]
  [210 175 161]
  [206 173 171]
  ...
  [ 44  48  46]
  [ 47  48  37]
  [ 44  46  24]]

 [[196 185 170]
  [195 184 171]
  [191 179 172]
  ...
  [ 49  44  32]
  [ 53  43  28]
  [ 59  42  33]]

 [[192 187 172]
  [185 180 165]
  [187 183 173]
  ...
  [ 44  47  40]
  [ 49  46  38]
  [ 55  49  46]]

 ...

 [[ 61  65  93]
  [ 52  61  80]
  [ 51  64  76]
  ..

[[[200 169 160]
  [213 185 178]
  [206 185 176]
  ...
  [ 38  43  27]
  [ 50  55  41]
  [ 45  51  38]]

 [[205 169 172]
  [209 172 174]
  [208 176 179]
  ...
  [ 43  55  38]
  [ 39  59  45]
  [ 32  55  46]]

 [[204 172 171]
  [202 169 170]
  [202 172 177]
  ...
  [ 50  50  36]
  [ 49  45  43]
  [ 51  49  49]]

 ...

 [[ 60  57  58]
  [ 63  53  56]
  [ 68  54  62]
  ...
  [126 122 128]
  [123 123 128]
  [111 118 119]]

 [[ 65  59  48]
  [ 64  53  48]
  [ 74  53  57]
  ...
  [128 126 133]
  [123 118 125]
  [123 114 126]]

 [[ 63  59  50]
  [ 69  59  57]
  [ 74  56  66]
  ...
  [129 129 130]
  [122 121 119]
  [121 118 113]]]
[[[200 184 187]
  [196 181 181]
  [197 176 177]
  ...
  [ 61  45  39]
  [ 69  42  30]
  [ 70  32  13]]

 [[201 180 183]
  [196 179 179]
  [199 184 180]
  ...
  [ 54  47  33]
  [ 45  45  23]
  [ 51  49  21]]

 [[196 176 178]
  [194 178 178]
  [200 185 183]
  ...
  [ 52  44  39]
  [ 55  42  35]
  [ 61  47  36]]

 ...

 [[ 68  60  58]
  [ 64  59  57]
  [ 62  60  57]
  ..

[[[204 189 164]
  [202 184 162]
  [210 183 169]
  ...
  [ 57  44  45]
  [ 46  36  44]
  [ 41  29  43]]

 [[199 183 157]
  [198 177 155]
  [205 177 162]
  ...
  [ 50  44  36]
  [ 48  40  39]
  [ 51  41  43]]

 [[193 186 157]
  [194 179 156]
  [199 183 166]
  ...
  [ 46  54  47]
  [ 42  51  42]
  [ 49  56  47]]

 ...

 [[ 34  71  78]
  [ 40  68  71]
  [ 49  63  65]
  ...
  [134 124 110]
  [130 128 114]
  [115 118 107]]

 [[ 55  64  84]
  [ 60  68  81]
  [ 61  64  69]
  ...
  [131 132 111]
  [127 134 117]
  [117 129 113]]

 [[ 69  54  77]
  [ 69  57  74]
  [ 68  62  72]
  ...
  [129 131 107]
  [127 130 119]
  [118 129 121]]]
[[[200 178 175]
  [202 180 176]
  [197 176 175]
  ...
  [ 50  48  50]
  [ 49  29  43]
  [ 60  19  52]]

 [[193 176 175]
  [197 178 176]
  [201 182 176]
  ...
  [ 39  48  43]
  [ 39  42  37]
  [ 44  36  41]]

 [[192 179 169]
  [191 178 168]
  [195 182 175]
  ...
  [ 41  47  45]
  [ 45  45  38]
  [ 46  42  33]]

 ...

 [[ 65  65  75]
  [ 59  60  66]
  [ 59  59  63]
  ..

[[[194 187 167]
  [197 184 168]
  [197 179 167]
  ...
  [ 42  42  49]
  [ 45  36  53]
  [ 45  31  55]]

 [[198 181 169]
  [194 177 167]
  [195 177 171]
  ...
  [ 52  51  55]
  [ 55  44  54]
  [ 65  48  59]]

 [[203 181 180]
  [191 173 173]
  [204 184 185]
  ...
  [ 46  46  47]
  [ 44  34  36]
  [ 57  39  35]]

 ...

 [[ 58  54  80]
  [ 54  51  74]
  [ 54  57  73]
  ...
  [132 133 125]
  [123 129 119]
  [117 123 115]]

 [[ 61  50  79]
  [ 59  51  76]
  [ 70  65  83]
  ...
  [125 122 118]
  [119 120 114]
  [120 122 119]]

 [[ 73  41  82]
  [ 64  36  68]
  [ 73  53  70]
  ...
  [131 130 131]
  [130 128 128]
  [131 131 130]]]
[[[201 186 164]
  [203 187 172]
  [194 180 173]
  ...
  [ 39  35  38]
  [ 54  39  41]
  [ 58  46  49]]

 [[194 187 160]
  [198 182 165]
  [203 180 173]
  ...
  [ 48  45  40]
  [ 46  42  37]
  [ 54  47  48]]

 [[199 183 164]
  [200 176 165]
  [208 179 175]
  ...
  [ 48  49  47]
  [ 47  47  47]
  [ 51  50  51]]

 ...

 [[ 57  54  73]
  [ 58  60  70]
  [ 52  59  56]
  ..

[[[196 188 171]
  [193 183 169]
  [196 186 173]
  ...
  [ 40  48  49]
  [ 42  45  44]
  [ 42  39  39]]

 [[203 174 167]
  [208 179 167]
  [207 183 168]
  ...
  [ 43  43  49]
  [ 48  38  44]
  [ 59  40  47]]

 [[194 180 166]
  [195 177 160]
  [205 184 169]
  ...
  [ 47  45  57]
  [ 50  43  54]
  [ 52  45  52]]

 ...

 [[ 56  54  69]
  [ 50  51  61]
  [ 53  61  69]
  ...
  [124 125 121]
  [124 116 117]
  [124 113 113]]

 [[ 39  57  69]
  [ 37  59  70]
  [ 53  71  80]
  ...
  [126 127 130]
  [129 122 130]
  [128 122 127]]

 [[ 53  70  82]
  [ 50  67  72]
  [ 55  66  72]
  ...
  [135 134 140]
  [129 126 133]
  [127 127 131]]]
[[[203 172 174]
  [206 178 179]
  [202 178 177]
  ...
  [ 51  47  42]
  [ 61  50  50]
  [ 63  50  51]]

 [[204 172 165]
  [204 177 173]
  [201 182 180]
  ...
  [ 54  58  43]
  [ 51  54  42]
  [ 45  47  42]]

 [[194 170 152]
  [201 180 165]
  [203 186 176]
  ...
  [ 52  60  37]
  [ 45  57  38]
  [ 41  54  42]]

 ...

 [[ 68  63  89]
  [ 57  53  74]
  [ 58  59  69]
  ..

[[[210 176 180]
  [203 176 176]
  [201 180 176]
  ...
  [ 41  50  30]
  [ 50  48  25]
  [ 55  37  17]]

 [[214 172 174]
  [206 174 170]
  [199 179 171]
  ...
  [ 50  52  46]
  [ 52  49  39]
  [ 48  38  30]]

 [[206 179 170]
  [201 172 165]
  [200 174 168]
  ...
  [ 43  50  40]
  [ 39  34  33]
  [ 59  44  48]]

 ...

 [[ 59  62  52]
  [ 56  64  55]
  [ 50  62  57]
  ...
  [124 132 114]
  [113 123 109]
  [108 114 104]]

 [[ 51  58  43]
  [ 53  71  58]
  [ 49  66  60]
  ...
  [127 131 126]
  [123 122 117]
  [122 117 113]]

 [[ 55  67  72]
  [ 47  63  68]
  [ 47  67  64]
  ...
  [136 131 133]
  [131 119 123]
  [133 112 115]]]
[[[195 188 182]
  [194 180 173]
  [201 177 173]
  ...
  [ 41  49  37]
  [ 44  47  44]
  [ 49  45  56]]

 [[191 178 169]
  [196 177 174]
  [197 172 173]
  ...
  [ 29  55  34]
  [ 27  43  32]
  [ 40  40  40]]

 [[200 174 169]
  [199 176 171]
  [205 184 184]
  ...
  [ 31  54  37]
  [ 35  52  42]
  [ 35  45  40]]

 ...

 [[ 49  60  71]
  [ 60  63  73]
  [ 47  48  60]
  ..

[[[203 181 183]
  [194 178 175]
  [193 187 178]
  ...
  [ 50  34  44]
  [ 54  32  39]
  [ 50  24  29]]

 [[207 178 176]
  [202 175 175]
  [198 177 175]
  ...
  [ 62  47  41]
  [ 56  38  39]
  [ 63  37  44]]

 [[200 173 173]
  [198 174 174]
  [200 181 182]
  ...
  [ 56  42  36]
  [ 56  28  34]
  [ 73  37  48]]

 ...

 [[ 64  67  75]
  [ 59  61  63]
  [ 59  57  55]
  ...
  [143 128 130]
  [138 125 131]
  [125 117 124]]

 [[ 64  55  76]
  [ 63  55  74]
  [ 67  57  70]
  ...
  [128 120 116]
  [130 124 125]
  [127 129 129]]

 [[ 64  56  90]
  [ 65  51  85]
  [ 66  48  76]
  ...
  [117 125 113]
  [126 128 119]
  [128 133 130]]]
[[[210 185 187]
  [197 176 178]
  [200 182 183]
  ...
  [ 33  54  49]
  [ 30  48  49]
  [ 36  47  51]]

 [[205 185 172]
  [200 180 171]
  [198 180 175]
  ...
  [ 46  55  39]
  [ 42  43  40]
  [ 51  45  53]]

 [[201 179 170]
  [206 185 176]
  [203 184 177]
  ...
  [ 47  53  42]
  [ 42  45  40]
  [ 47  49  48]]

 ...

 [[ 66  59  76]
  [ 67  61  75]
  [ 62  57  65]
  ..

[[[202 177 182]
  [203 180 185]
  [203 183 186]
  ...
  [ 44  50  39]
  [ 42  46  31]
  [ 53  51  38]]

 [[198 180 182]
  [196 178 178]
  [201 180 181]
  ...
  [ 43  45  33]
  [ 46  42  32]
  [ 57  48  40]]

 [[193 182 173]
  [192 178 169]
  [199 183 177]
  ...
  [ 38  42  39]
  [ 46  38  40]
  [ 63  41  46]]

 ...

 [[ 60  63  51]
  [ 68  70  61]
  [ 66  69  72]
  ...
  [134 136 128]
  [130 133 123]
  [122 127 115]]

 [[ 44  64  62]
  [ 53  71  65]
  [ 63  67  67]
  ...
  [126 125 122]
  [124 125 119]
  [122 125 119]]

 [[ 59  71  84]
  [ 61  67  78]
  [ 63  61  69]
  ...
  [127 127 122]
  [123 124 125]
  [127 127 130]]]
[[[210 179 165]
  [216 182 167]
  [209 176 168]
  ...
  [ 39  44  42]
  [ 46  47  39]
  [ 46  32  29]]

 [[209 174 165]
  [211 176 166]
  [206 179 165]
  ...
  [ 53  48  38]
  [ 51  52  39]
  [ 43  43  29]]

 [[204 173 177]
  [204 173 175]
  [206 180 177]
  ...
  [ 53  47  28]
  [ 50  49  29]
  [ 52  52  33]]

 ...

 [[ 61  53  80]
  [ 61  56  81]
  [ 57  59  82]
  ..

[[[211 187 186]
  [207 180 180]
  [205 184 187]
  ...
  [ 48  43  50]
  [ 55  39  57]
  [ 55  29  64]]

 [[197 172 164]
  [206 183 176]
  [202 186 185]
  ...
  [ 56  41  40]
  [ 53  42  44]
  [ 49  41  52]]

 [[199 185 175]
  [201 183 175]
  [201 182 177]
  ...
  [ 52  35  34]
  [ 47  33  31]
  [ 54  54  50]]

 ...

 [[ 66  66  77]
  [ 66  66  71]
  [ 62  60  62]
  ...
  [143 133 127]
  [137 126 124]
  [139 128 127]]

 [[ 62  55  67]
  [ 73  66  72]
  [ 72  66  69]
  ...
  [130 123 124]
  [133 120 118]
  [132 121 113]]

 [[ 69  56  94]
  [ 67  54  84]
  [ 74  60  81]
  ...
  [127 114 129]
  [131 117 125]
  [129 121 119]]]
[[[203 178 179]
  [201 178 178]
  [200 177 179]
  ...
  [ 57  38  32]
  [ 70  36  29]
  [ 78  37  32]]

 [[205 171 178]
  [207 175 176]
  [198 175 170]
  ...
  [ 55  50  36]
  [ 53  43  28]
  [ 60  44  31]]

 [[188 172 175]
  [190 172 171]
  [195 178 173]
  ...
  [ 48  49  40]
  [ 56  47  39]
  [ 61  44  39]]

 ...

 [[ 51  57  80]
  [ 56  57  79]
  [ 63  50  77]
  ..

[[[208 176 184]
  [207 175 184]
  [210 176 189]
  ...
  [ 39  54  48]
  [ 40  46  48]
  [ 38  46  52]]

 [[207 169 183]
  [205 172 186]
  [203 174 191]
  ...
  [ 36  55  33]
  [ 40  51  40]
  [ 49  55  51]]

 [[194 164 163]
  [194 170 171]
  [196 179 184]
  ...
  [ 48  44  43]
  [ 46  32  28]
  [ 65  47  35]]

 ...

 [[ 49  65  78]
  [ 52  61  72]
  [ 52  55  63]
  ...
  [127 137 117]
  [130 130 114]
  [138 123 116]]

 [[ 50  66  60]
  [ 49  69  64]
  [ 51  67  68]
  ...
  [137 133 126]
  [134 126 117]
  [132 119 114]]

 [[ 59  80  50]
  [ 52  71  46]
  [ 60  63  55]
  ...
  [139 119 116]
  [133 123 108]
  [125 124 109]]]
[[[207 178 182]
  [208 179 182]
  [207 180 185]
  ...
  [ 52  42  53]
  [ 45  40  60]
  [ 42  37  64]]

 [[198 179 167]
  [194 176 166]
  [203 185 180]
  ...
  [ 50  39  33]
  [ 59  39  38]
  [ 65  32  41]]

 [[197 179 174]
  [192 176 170]
  [198 185 177]
  ...
  [ 54  49  36]
  [ 56  36  26]
  [ 67  42  33]]

 ...

 [[ 63  56  44]
  [ 68  61  60]
  [ 58  61  69]
  ..

[[[198 199 171]
  [193 191 167]
  [197 185 169]
  ...
  [ 42  46  34]
  [ 43  47  46]
  [ 40  45  55]]

 [[182 181 163]
  [187 183 164]
  [193 180 163]
  ...
  [ 42  47  24]
  [ 41  37  30]
  [ 55  46  53]]

 [[194 184 170]
  [192 181 166]
  [199 184 173]
  ...
  [ 47  50  41]
  [ 48  44  35]
  [ 60  54  49]]

 ...

 [[ 50  61  70]
  [ 50  60  67]
  [ 50  64  69]
  ...
  [133 139 128]
  [124 136 130]
  [123 135 131]]

 [[ 52  56  53]
  [ 54  61  58]
  [ 54  67  65]
  ...
  [137 142 133]
  [132 136 126]
  [131 136 128]]

 [[ 55  55  69]
  [ 57  65  75]
  [ 50  64  68]
  ...
  [134 131 116]
  [128 130 118]
  [132 139 128]]]
[[[209 190 172]
  [201 184 164]
  [203 181 167]
  ...
  [ 49  39  36]
  [ 50  44  36]
  [ 53  44  43]]

 [[200 178 170]
  [199 178 171]
  [202 181 173]
  ...
  [ 59  43  42]
  [ 50  43  34]
  [ 54  55  39]]

 [[188 185 171]
  [189 178 168]
  [200 182 176]
  ...
  [ 58  36  39]
  [ 67  32  32]
  [ 74  34  34]]

 ...

 [[ 65  54  83]
  [ 66  57  79]
  [ 62  57  72]
  ..

[[[210 178 181]
  [205 174 176]
  [214 182 189]
  ...
  [ 57  40  61]
  [ 55  34  58]
  [ 55  34  61]]

 [[197 183 181]
  [193 173 168]
  [201 176 175]
  ...
  [ 51  46  43]
  [ 51  40  39]
  [ 52  31  35]]

 [[196 181 179]
  [188 175 169]
  [191 181 175]
  ...
  [ 50  46  40]
  [ 55  42  39]
  [ 62  40  37]]

 ...

 [[ 58  47  84]
  [ 62  56  88]
  [ 54  56  79]
  ...
  [ 81  82  98]
  [ 79  81  97]
  [ 60  62  84]]

 [[ 51  59  77]
  [ 57  68  88]
  [ 52  61  81]
  ...
  [ 79  72  98]
  [ 73  75  99]
  [ 57  66  93]]

 [[ 51  66  82]
  [ 57  72  86]
  [ 46  55  70]
  ...
  [ 76  67 100]
  [ 73  77 110]
  [ 57  70 103]]]
[[[199 177 181]
  [196 174 178]
  [202 179 184]
  ...
  [ 61  45  34]
  [ 54  44  31]
  [ 52  44  33]]

 [[185 176 172]
  [191 181 175]
  [201 184 181]
  ...
  [ 44  49  41]
  [ 43  44  35]
  [ 48  47  37]]

 [[193 180 183]
  [192 175 177]
  [197 174 177]
  ...
  [ 51  57  52]
  [ 51  48  44]
  [ 52  49  42]]

 ...

 [[ 52  63  57]
  [ 56  67  68]
  [ 57  66  74]
  ..

[[[202 183 175]
  [208 185 178]
  [204 185 174]
  ...
  [ 38  53  55]
  [ 45  47  45]
  [ 57  35  36]]

 [[205 175 174]
  [210 179 177]
  [205 180 175]
  ...
  [ 35  49  49]
  [ 32  42  40]
  [ 40  43  39]]

 [[206 172 172]
  [209 175 173]
  [207 177 176]
  ...
  [ 43  59  64]
  [ 43  50  55]
  [ 42  44  46]]

 ...

 [[ 62  58  89]
  [ 54  51  78]
  [ 58  54  81]
  ...
  [ 83  70 115]
  [ 78  77 104]
  [ 56  60  70]]

 [[ 77  59  84]
  [ 73  57  79]
  [ 69  59  74]
  ...
  [ 81  61  97]
  [ 81  68  96]
  [ 73  63  83]]

 [[ 73  59  82]
  [ 78  66  80]
  [ 63  59  66]
  ...
  [ 83  78  96]
  [ 83  79 104]
  [ 84  75 105]]]
[[[211 172 177]
  [208 175 179]
  [201 175 175]
  ...
  [ 54  43  44]
  [ 45  41  43]
  [ 41  44  50]]

 [[207 173 169]
  [204 177 172]
  [201 182 174]
  ...
  [ 53  52  49]
  [ 43  43  44]
  [ 49  51  54]]

 [[203 173 171]
  [197 174 167]
  [196 182 168]
  ...
  [ 48  47  44]
  [ 51  42  45]
  [ 53  43  50]]

 ...

 [[ 66  57  82]
  [ 68  55  73]
  [ 72  49  60]
  ..

[[[194 181 171]
  [197 181 172]
  [198 173 173]
  ...
  [ 43  42  35]
  [ 47  43  37]
  [ 47  41  41]]

 [[199 179 161]
  [202 181 169]
  [208 182 177]
  ...
  [ 37  40  31]
  [ 42  41  29]
  [ 54  50  38]]

 [[200 173 168]
  [198 173 166]
  [204 181 176]
  ...
  [ 39  50  37]
  [ 38  35  27]
  [ 53  37  31]]

 ...

 [[ 62  51  78]
  [ 63  54  76]
  [ 66  56  75]
  ...
  [ 80  70  98]
  [ 82  72 102]
  [ 70  59  92]]

 [[ 54  55  78]
  [ 57  56  80]
  [ 60  55  84]
  ...
  [ 81  76 104]
  [ 83  76 100]
  [ 78  74  93]]

 [[ 63  57  91]
  [ 62  57  85]
  [ 63  53  83]
  ...
  [ 84  79 107]
  [ 80  77 100]
  [ 82  79  95]]]
[[[200 185 170]
  [199 177 168]
  [202 172 170]
  ...
  [ 52  45  33]
  [ 62  48  41]
  [ 57  37  36]]

 [[194 172 174]
  [198 174 177]
  [196 170 175]
  ...
  [ 52  46  42]
  [ 47  40  37]
  [ 60  53  51]]

 [[197 171 178]
  [198 171 176]
  [201 174 177]
  ...
  [ 44  52  52]
  [ 44  50  47]
  [ 51  56  49]]

 ...

 [[ 51  71  67]
  [ 47  63  66]
  [ 52  59  71]
  ..

[[[193 175 182]
  [195 181 183]
  [194 187 185]
  ...
  [ 45  51  40]
  [ 47  44  43]
  [ 44  28  31]]

 [[204 179 190]
  [201 179 185]
  [199 178 180]
  ...
  [ 54  50  34]
  [ 51  40  38]
  [ 53  32  42]]

 [[194 180 172]
  [197 178 174]
  [200 175 174]
  ...
  [ 51  53  40]
  [ 48  43  35]
  [ 51  43  35]]

 ...

 [[ 66  69  59]
  [ 57  60  50]
  [ 56  56  49]
  ...
  [ 74  66  99]
  [ 82  78 109]
  [ 56  54  83]]

 [[ 58  51  53]
  [ 67  67  68]
  [ 66  69  70]
  ...
  [ 69  60 104]
  [ 70  69 103]
  [ 72  80 106]]

 [[ 67  66  75]
  [ 75  74  85]
  [ 67  64  75]
  ...
  [ 73  62 112]
  [ 68  68 108]
  [ 70  83 113]]]
[[[202 182 174]
  [201 183 174]
  [195 183 183]
  ...
  [ 56  47  54]
  [ 51  38  42]
  [ 51  38  36]]

 [[195 184 180]
  [196 180 175]
  [198 178 178]
  ...
  [ 52  50  40]
  [ 40  45  29]
  [ 40  52  32]]

 [[195 180 181]
  [195 179 177]
  [198 182 179]
  ...
  [ 51  49  39]
  [ 48  43  33]
  [ 56  52  37]]

 ...

 [[ 50  67  69]
  [ 54  64  64]
  [ 59  58  61]
  ..

[[[195 174 181]
  [204 178 187]
  [205 178 180]
  ...
  [ 44  49  53]
  [ 50  46  52]
  [ 52  46  53]]

 [[202 181 184]
  [199 174 178]
  [197 173 173]
  ...
  [ 47  51  44]
  [ 44  43  39]
  [ 47  41  43]]

 [[203 177 180]
  [195 168 170]
  [197 176 173]
  ...
  [ 54  54  49]
  [ 38  36  36]
  [ 45  43  45]]

 ...

 [[ 59  62  55]
  [ 67  68  62]
  [ 58  57  57]
  ...
  [ 71  82 103]
  [ 68  74 101]
  [ 58  62  93]]

 [[ 57  51  44]
  [ 69  61  64]
  [ 69  61  71]
  ...
  [ 74  76 101]
  [ 80  79 105]
  [ 70  72  97]]

 [[ 64  62  84]
  [ 68  65  90]
  [ 62  59  84]
  ...
  [ 81  63  97]
  [ 93  65  98]
  [ 98  77 102]]]
[[[199 183 173]
  [198 179 171]
  [205 179 178]
  ...
  [ 48  54  48]
  [ 49  46  46]
  [ 53  41  41]]

 [[186 179 164]
  [188 174 165]
  [195 173 172]
  ...
  [ 41  50  40]
  [ 43  39  37]
  [ 55  35  38]]

 [[196 182 168]
  [195 180 168]
  [197 180 175]
  ...
  [ 43  51  46]
  [ 38  40  44]
  [ 44  42  53]]

 ...

 [[ 53  61  71]
  [ 56  64  74]
  [ 64  63  76]
  ..

[[[204 179 170]
  [205 182 174]
  [203 182 171]
  ...
  [ 62  45  46]
  [ 40  31  25]
  [ 52  44  37]]

 [[203 174 186]
  [198 170 178]
  [202 173 175]
  ...
  [ 51  43  41]
  [ 50  38  36]
  [ 62  44  44]]

 [[200 169 191]
  [194 165 181]
  [199 176 182]
  ...
  [ 47  48  44]
  [ 51  46  41]
  [ 54  45  41]]

 ...

 [[ 53  64  65]
  [ 55  64  69]
  [ 58  59  71]
  ...
  [ 83  74 104]
  [ 73  74 102]
  [ 55  71  96]]

 [[ 64  50  69]
  [ 65  54  73]
  [ 60  50  74]
  ...
  [ 71  72  94]
  [ 74  78 103]
  [ 62  79 100]]

 [[ 75  46  89]
  [ 64  44  76]
  [ 56  48  67]
  ...
  [ 71  77  99]
  [ 73  84 102]
  [ 69  88 105]]]
[[[206 178 175]
  [202 176 167]
  [202 177 169]
  ...
  [ 63  50  48]
  [ 58  46  48]
  [ 44  37  46]]

 [[209 174 171]
  [207 174 171]
  [209 177 178]
  ...
  [ 61  41  32]
  [ 53  33  29]
  [ 65  50  51]]

 [[202 178 174]
  [196 173 171]
  [204 180 181]
  ...
  [ 51  41  36]
  [ 61  38  37]
  [ 74  45  50]]

 ...

 [[ 43  71  77]
  [ 58  74  84]
  [ 50  55  69]
  ..

[[[216 176 173]
  [215 172 177]
  [212 168 179]
  ...
  [ 46  42  52]
  [ 55  44  52]
  [ 50  39  52]]

 [[206 172 175]
  [204 170 176]
  [204 169 177]
  ...
  [ 51  48  44]
  [ 48  43  42]
  [ 48  43  46]]

 [[201 175 171]
  [199 175 172]
  [201 180 175]
  ...
  [ 46  49  42]
  [ 45  47  36]
  [ 53  49  41]]

 ...

 [[ 51  56  69]
  [ 57  61  75]
  [ 59  59  78]
  ...
  [ 90  81 107]
  [ 85  74 103]
  [ 75  66  96]]

 [[ 60  61  70]
  [ 63  68  75]
  [ 59  64  73]
  ...
  [ 82  78 114]
  [ 77  74 106]
  [ 74  70  98]]

 [[ 59  59  80]
  [ 58  67  73]
  [ 53  70  62]
  ...
  [ 62  80 110]
  [ 59  79  99]
  [ 71  82  97]]]
[[[207 191 167]
  [202 184 167]
  [197 178 172]
  ...
  [ 37  49  50]
  [ 37  38  40]
  [ 45  35  39]]

 [[198 181 160]
  [200 181 166]
  [200 178 172]
  ...
  [ 49  51  44]
  [ 38  41  37]
  [ 52  47  47]]

 [[192 178 163]
  [195 180 166]
  [207 188 174]
  ...
  [ 65  57  50]
  [ 59  46  42]
  [ 54  40  36]]

 ...

 [[ 58  65  72]
  [ 54  63  66]
  [ 56  65  69]
  ..

[[[201 179 177]
  [204 182 173]
  [207 181 172]
  ...
  [ 56  49  38]
  [ 51  42  33]
  [ 54  32  33]]

 [[201 179 174]
  [198 175 171]
  [198 176 173]
  ...
  [ 57  51  41]
  [ 50  47  42]
  [ 47  38  46]]

 [[191 175 177]
  [190 173 176]
  [192 175 179]
  ...
  [ 47  46  51]
  [ 46  46  51]
  [ 46  48  52]]

 ...

 [[ 52  61  76]
  [ 59  64  86]
  [ 57  60  86]
  ...
  [ 75  80 106]
  [ 73  73 106]
  [ 66  64  99]]

 [[ 59  62  72]
  [ 57  66  76]
  [ 54  65  74]
  ...
  [ 72  76 102]
  [ 73  76  99]
  [ 72  74  98]]

 [[ 52  67  84]
  [ 52  65  79]
  [ 48  66  78]
  ...
  [ 73  76  97]
  [ 72  80  92]
  [ 66  74  82]]]
[[[219 179 175]
  [211 176 174]
  [208 180 185]
  ...
  [ 55  47  50]
  [ 49  40  49]
  [ 48  42  57]]

 [[213 174 178]
  [211 172 178]
  [211 172 184]
  ...
  [ 52  42  40]
  [ 59  44  47]
  [ 58  45  54]]

 [[209 171 184]
  [204 171 182]
  [204 177 184]
  ...
  [ 50  45  44]
  [ 49  31  37]
  [ 65  44  48]]

 ...

 [[ 56  72  78]
  [ 51  59  71]
  [ 50  50  66]
  ..

[[[200 183 186]
  [199 177 180]
  [203 175 179]
  ...
  [ 52  53  52]
  [ 45  47  51]
  [ 40  44  57]]

 [[194 169 163]
  [201 174 169]
  [207 175 178]
  ...
  [ 54  55  45]
  [ 37  33  33]
  [ 47  40  47]]

 [[201 177 170]
  [206 176 173]
  [211 177 179]
  ...
  [ 57  52  38]
  [ 47  43  31]
  [ 44  49  32]]

 ...

 [[ 54  60  80]
  [ 53  56  71]
  [ 52  51  65]
  ...
  [ 79  69 106]
  [ 85  73 109]
  [ 69  54  94]]

 [[ 44  54  57]
  [ 54  63  67]
  [ 59  60  72]
  ...
  [ 76  74 101]
  [ 83  73 110]
  [ 78  58 108]]

 [[ 60  63  63]
  [ 63  63  64]
  [ 66  64  66]
  ...
  [ 70  73  93]
  [ 75  78  96]
  [ 74  75  99]]]
[[[200 183 172]
  [204 178 170]
  [206 174 169]
  ...
  [ 62  38  42]
  [ 60  36  41]
  [ 52  32  41]]

 [[204 180 174]
  [206 179 177]
  [211 181 179]
  ...
  [ 50  47  39]
  [ 54  43  42]
  [ 59  37  53]]

 [[203 168 174]
  [202 166 174]
  [204 172 178]
  ...
  [ 46  47  43]
  [ 60  46  47]
  [ 62  38  46]]

 ...

 [[ 58  74  72]
  [ 57  68  67]
  [ 59  56  63]
  ..

[[[202 185 187]
  [201 180 178]
  [201 181 172]
  ...
  [ 51  52  36]
  [ 47  43  39]
  [ 51  41  54]]

 [[206 177 177]
  [198 169 170]
  [200 177 172]
  ...
  [ 46  53  44]
  [ 43  46  40]
  [ 45  50  42]]

 [[203 171 178]
  [196 166 173]
  [206 177 182]
  ...
  [ 51  58  46]
  [ 50  49  34]
  [ 53  51  23]]

 ...

 [[ 53  49  74]
  [ 62  50  80]
  [ 68  45  87]
  ...
  [ 72  74 106]
  [ 78  73 114]
  [ 63  48  99]]

 [[ 64  53  64]
  [ 73  62  81]
  [ 68  54  84]
  ...
  [ 71  76 107]
  [ 74  78 108]
  [ 73  70 104]]

 [[ 75  56  71]
  [ 76  58  73]
  [ 72  56  74]
  ...
  [ 71  82 115]
  [ 82  80 109]
  [ 89  73  99]]]
[[[198 176 170]
  [202 181 178]
  [208 184 183]
  ...
  [ 67  36  42]
  [ 60  40  43]
  [ 55  38  40]]

 [[210 182 187]
  [203 177 180]
  [211 182 184]
  ...
  [ 59  42  41]
  [ 48  35  33]
  [ 53  36  37]]

 [[198 174 173]
  [196 172 173]
  [205 177 183]
  ...
  [ 51  52  37]
  [ 50  47  40]
  [ 55  50  50]]

 ...

 [[ 56  57  81]
  [ 53  57  76]
  [ 49  61  72]
  ..

[[[188 177 179]
  [196 186 186]
  [194 184 185]
  ...
  [ 51  42  35]
  [ 56  41  33]
  [ 63  39  37]]

 [[197 181 174]
  [201 185 179]
  [199 182 176]
  ...
  [ 54  47  38]
  [ 49  42  38]
  [ 52  42  43]]

 [[199 177 175]
  [200 175 176]
  [200 176 178]
  ...
  [ 52  45  42]
  [ 49  43  43]
  [ 52  47  47]]

 ...

 [[ 77  60  79]
  [ 70  53  71]
  [ 63  50  71]
  ...
  [ 81  75 102]
  [ 85  73 106]
  [ 70  52  92]]

 [[ 72  51  70]
  [ 67  51  69]
  [ 60  51  73]
  ...
  [ 77  70  99]
  [ 76  65 100]
  [ 71  59 100]]

 [[ 77  53  71]
  [ 68  48  69]
  [ 66  48  79]
  ...
  [ 76  74  98]
  [ 82  78 108]
  [ 81  72 107]]]
[[[206 186 168]
  [200 181 168]
  [195 179 173]
  ...
  [ 36  49  49]
  [ 36  55  55]
  [ 41  51  56]]

 [[200 173 174]
  [200 175 178]
  [201 178 182]
  ...
  [ 49  52  39]
  [ 50  53  38]
  [ 52  49  33]]

 [[205 172 176]
  [199 171 175]
  [202 180 181]
  ...
  [ 45  52  34]
  [ 51  48  23]
  [ 61  46  18]]

 ...

 [[ 69  58  88]
  [ 63  54  79]
  [ 57  53  68]
  ..

[[[202 185 188]
  [199 182 181]
  [198 181 172]
  ...
  [ 49  56  36]
  [ 55  41  29]
  [ 62  33  36]]

 [[199 176 178]
  [198 178 177]
  [197 181 179]
  ...
  [ 52  49  31]
  [ 57  40  23]
  [ 67  36  23]]

 [[203 176 175]
  [196 174 171]
  [196 177 180]
  ...
  [ 48  52  38]
  [ 45  37  23]
  [ 54  41  27]]

 ...

 [[ 62  59  77]
  [ 63  60  75]
  [ 62  59  70]
  ...
  [ 84  76 104]
  [ 78  72 100]
  [ 76  73  97]]

 [[ 52  64  73]
  [ 58  67  79]
  [ 60  59  72]
  ...
  [ 75  74 105]
  [ 73  75  98]
  [ 66  78  92]]

 [[ 50  62  80]
  [ 47  58  74]
  [ 56  63  78]
  ...
  [ 74  68 108]
  [ 70  67  94]
  [ 79  86  99]]]
[[[214 180 172]
  [209 177 172]
  [208 178 177]
  ...
  [ 66  42  49]
  [ 53  42  47]
  [ 51  44  50]]

 [[211 185 163]
  [211 182 169]
  [212 182 179]
  ...
  [ 45  50  37]
  [ 42  47  42]
  [ 47  48  54]]

 [[201 175 171]
  [200 171 168]
  [203 174 174]
  ...
  [ 25  52  30]
  [ 25  54  36]
  [ 28  57  49]]

 ...

 [[ 66  58  79]
  [ 62  56  73]
  [ 56  49  67]
  ..

[[[203 176 164]
  [201 183 171]
  [193 188 178]
  ...
  [ 47  45  45]
  [ 52  38  43]
  [ 60  40  45]]

 [[201 173 169]
  [203 176 175]
  [199 176 179]
  ...
  [ 49  41  45]
  [ 42  38  40]
  [ 47  41  48]]

 [[200 172 177]
  [200 172 179]
  [201 174 183]
  ...
  [ 53  44  50]
  [ 48  39  40]
  [ 49  43  41]]

 ...

 [[ 62  61  66]
  [ 60  58  62]
  [ 61  59  63]
  ...
  [ 84  71 107]
  [ 87  78 115]
  [ 55  58  93]]

 [[ 74  55  75]
  [ 77  64  79]
  [ 69  57  73]
  ...
  [ 75  66 100]
  [ 65  71  97]
  [ 50  73  94]]

 [[ 74  47  85]
  [ 75  52  77]
  [ 66  45  65]
  ...
  [ 66  79 100]
  [ 57  75  94]
  [ 65  87 105]]]
[[[204 183 175]
  [203 182 172]
  [205 185 177]
  ...
  [ 42  52  29]
  [ 49  48  35]
  [ 53  37  40]]

 [[200 184 181]
  [195 178 176]
  [206 188 183]
  ...
  [ 41  46  21]
  [ 40  41  27]
  [ 51  48  45]]

 [[194 181 180]
  [188 174 174]
  [199 185 179]
  ...
  [ 53  52  46]
  [ 44  43  39]
  [ 48  50  42]]

 ...

 [[ 61  65  75]
  [ 61  63  72]
  [ 60  59  69]
  ..

[[[197 180 179]
  [197 180 178]
  [199 182 181]
  ...
  [ 47  47  33]
  [ 47  45  35]
  [ 57  49  42]]

 [[206 175 170]
  [206 175 170]
  [212 182 178]
  ...
  [ 48  45  30]
  [ 54  42  38]
  [ 62  46  52]]

 [[199 175 175]
  [202 176 173]
  [210 182 176]
  ...
  [ 43  43  42]
  [ 49  41  44]
  [ 55  50  57]]

 ...

 [[ 62  60  75]
  [ 60  60  73]
  [ 55  63  71]
  ...
  [ 90  75  96]
  [ 83  73 103]
  [ 68  67  98]]

 [[ 64  53  57]
  [ 64  58  63]
  [ 61  57  72]
  ...
  [ 85  79 102]
  [ 81  77 104]
  [ 73  67  95]]

 [[ 58  67  68]
  [ 52  58  65]
  [ 63  58  74]
  ...
  [ 87  83  96]
  [ 86  81  92]
  [ 83  77  81]]]
[[[203 184 179]
  [200 179 172]
  [205 181 167]
  ...
  [ 50  50  45]
  [ 50  40  42]
  [ 52  40  50]]

 [[197 189 175]
  [195 185 170]
  [200 188 169]
  ...
  [ 44  46  41]
  [ 41  35  35]
  [ 54  43  48]]

 [[188 179 177]
  [185 171 169]
  [199 181 175]
  ...
  [ 47  45  46]
  [ 51  45  45]
  [ 48  49  45]]

 ...

 [[ 63  59  78]
  [ 61  54  72]
  [ 60  56  72]
  ..

[[[204 183 182]
  [198 176 176]
  [197 183 175]
  ...
  [ 52  47  61]
  [ 58  47  55]
  [ 57  45  49]]

 [[200 178 176]
  [198 172 171]
  [200 177 174]
  ...
  [ 51  38  39]
  [ 57  42  45]
  [ 58  39  45]]

 [[198 177 176]
  [202 175 175]
  [203 174 174]
  ...
  [ 50  45  33]
  [ 57  46  40]
  [ 49  34  34]]

 ...

 [[ 43  67  79]
  [ 54  70  83]
  [ 53  55  73]
  ...
  [ 71  74 107]
  [ 78  71 112]
  [ 71  62 107]]

 [[ 47  47  61]
  [ 66  64  82]
  [ 61  57  79]
  ...
  [ 73  70 104]
  [ 84  74 110]
  [ 83  71 105]]

 [[ 67  63  69]
  [ 67  61  71]
  [ 70  58  71]
  ...
  [ 79  85 105]
  [ 80  84 100]
  [ 86  86  96]]]
[[[205 181 188]
  [205 178 182]
  [208 176 175]
  ...
  [ 54  44  48]
  [ 54  41  40]
  [ 59  34  39]]

 [[196 182 181]
  [199 178 177]
  [202 178 173]
  ...
  [ 48  44  31]
  [ 46  40  30]
  [ 54  45  41]]

 [[199 183 181]
  [196 178 174]
  [201 181 172]
  ...
  [ 45  51  35]
  [ 40  44  33]
  [ 44  45  40]]

 ...

 [[ 61  58  71]
  [ 63  62  73]
  [ 67  61  76]
  ..

[[[212 180 182]
  [203 170 171]
  [211 176 175]
  ...
  [ 45  50  54]
  [ 43  47  48]
  [ 47  44  51]]

 [[205 172 176]
  [202 169 173]
  [202 171 175]
  ...
  [ 48  45  45]
  [ 45  40  41]
  [ 48  40  45]]

 [[203 174 172]
  [204 174 177]
  [196 172 177]
  ...
  [ 45  51  48]
  [ 49  45  46]
  [ 55  42  49]]

 ...

 [[ 57  58  81]
  [ 51  52  74]
  [ 55  54  73]
  ...
  [ 93  89  96]
  [ 89  87  96]
  [ 70  68  79]]

 [[ 53  53  80]
  [ 53  53  76]
  [ 58  57  76]
  ...
  [ 90  88  98]
  [ 89  84 104]
  [ 81  77 102]]

 [[ 60  61  88]
  [ 56  56  78]
  [ 62  58  81]
  ...
  [ 98  98 100]
  [ 83  80  91]
  [ 85  82 101]]]
[[[199 179 186]
  [196 176 183]
  [197 177 183]
  ...
  [ 54  46  53]
  [ 64  45  57]
  [ 57  31  49]]

 [[200 171 182]
  [201 172 178]
  [202 176 180]
  ...
  [ 49  32  33]
  [ 56  34  34]
  [ 60  30  33]]

 [[197 172 178]
  [196 170 175]
  [200 178 180]
  ...
  [ 43  48  43]
  [ 49  48  38]
  [ 52  46  33]]

 ...

 [[ 57  66  92]
  [ 56  57  85]
  [ 57  56  77]
  ..

[[[197 183 173]
  [194 178 172]
  [197 179 176]
  ...
  [ 45  50  40]
  [ 40  52  35]
  [ 28  50  26]]

 [[197 177 175]
  [197 176 176]
  [197 181 184]
  ...
  [ 39  44  32]
  [ 46  47  39]
  [ 53  50  47]]

 [[206 174 177]
  [199 171 176]
  [199 181 183]
  ...
  [ 44  48  45]
  [ 47  43  46]
  [ 58  50  58]]

 ...

 [[ 62  65  67]
  [ 61  62  68]
  [ 61  66  75]
  ...
  [ 82  79  99]
  [ 84  74 102]
  [ 76  64  94]]

 [[ 57  49  60]
  [ 65  60  72]
  [ 62  62  74]
  ...
  [ 69  75  87]
  [ 78  71  90]
  [ 80  68  94]]

 [[ 70  56  78]
  [ 73  63  79]
  [ 64  58  67]
  ...
  [ 85  87  92]
  [ 87  82  92]
  [ 91  78  94]]]
[[[202 180 171]
  [209 183 176]
  [205 177 175]
  ...
  [ 66  52  42]
  [ 56  50  44]
  [ 50  46  42]]

 [[195 177 165]
  [200 181 169]
  [200 180 174]
  ...
  [ 50  47  22]
  [ 44  50  28]
  [ 47  53  39]]

 [[187 171 176]
  [196 177 179]
  [202 175 176]
  ...
  [ 42  48  41]
  [ 44  43  34]
  [ 56  51  38]]

 ...

 [[ 52  63  55]
  [ 53  69  65]
  [ 46  69  72]
  ..

[[[201 180 175]
  [194 180 172]
  [198 186 178]
  ...
  [ 36  45  41]
  [ 41  42  39]
  [ 51  47  46]]

 [[196 175 179]
  [195 176 177]
  [201 184 179]
  ...
  [ 45  50  48]
  [ 42  43  39]
  [ 48  48  41]]

 [[202 176 174]
  [200 176 173]
  [204 180 177]
  ...
  [ 39  44  41]
  [ 47  47  37]
  [ 53  49  32]]

 ...

 [[ 64  59  74]
  [ 64  58  69]
  [ 66  55  67]
  ...
  [ 81  72 102]
  [ 82  69 113]
  [ 69  55 108]]

 [[ 59  51  80]
  [ 60  59  78]
  [ 57  61  68]
  ...
  [ 71  65  98]
  [ 70  61 111]
  [ 65  57 118]]

 [[ 54  51  66]
  [ 62  63  79]
  [ 59  61  70]
  ...
  [ 70  84 113]
  [ 55  63 108]
  [ 70  70 128]]]
[[[213 173 173]
  [214 173 173]
  [218 179 173]
  ...
  [ 48  29  41]
  [ 50  41  57]
  [ 43  43  65]]

 [[211 175 166]
  [210 175 167]
  [203 174 167]
  ...
  [ 50  50  35]
  [ 46  51  38]
  [ 40  53  46]]

 [[201 178 177]
  [198 177 174]
  [201 179 179]
  ...
  [ 49  52  38]
  [ 42  51  30]
  [ 37  52  23]]

 ...

 [[ 69  62  80]
  [ 62  52  72]
  [ 61  53  69]
  ..

[[[202 184 177]
  [203 180 175]
  [200 175 176]
  ...
  [ 47  42  44]
  [ 43  38  39]
  [ 39  36  39]]

 [[208 178 175]
  [199 175 171]
  [200 181 180]
  ...
  [ 55  53  49]
  [ 53  44  38]
  [ 57  42  46]]

 [[203 174 178]
  [199 174 174]
  [201 181 175]
  ...
  [ 54  48  41]
  [ 55  44  35]
  [ 59  46  39]]

 ...

 [[ 66  60  68]
  [ 59  52  57]
  [ 58  58  62]
  ...
  [ 78  73 104]
  [ 81  73 105]
  [ 68  59  92]]

 [[ 69  64  62]
  [ 63  59  62]
  [ 56  60  69]
  ...
  [ 84  74 104]
  [ 82  73 105]
  [ 73  61 101]]

 [[ 69  65  81]
  [ 64  61  76]
  [ 57  63  72]
  ...
  [ 76  72  95]
  [ 71  73 100]
  [ 74  75 113]]]
[[[200 180 184]
  [199 181 182]
  [200 181 181]
  ...
  [ 64  37  41]
  [ 57  38  52]
  [ 54  40  71]]

 [[201 182 180]
  [195 176 177]
  [201 179 183]
  ...
  [ 60  34  45]
  [ 55  32  46]
  [ 56  40  56]]

 [[203 175 179]
  [200 176 179]
  [202 178 182]
  ...
  [ 54  44  52]
  [ 52  36  39]
  [ 53  42  36]]

 ...

 [[ 56  58  62]
  [ 64  65  68]
  [ 62  60  65]
  ..

[[[197 191 161]
  [204 187 169]
  [200 170 168]
  ...
  [ 55  48  32]
  [ 51  42  30]
  [ 60  45  38]]

 [[199 184 161]
  [198 183 167]
  [198 176 175]
  ...
  [ 56  52  37]
  [ 53  46  36]
  [ 58  43  36]]

 [[198 178 176]
  [200 175 178]
  [203 174 181]
  ...
  [ 49  54  45]
  [ 48  49  41]
  [ 47  44  35]]

 ...

 [[ 65  60  67]
  [ 59  54  63]
  [ 58  52  66]
  ...
  [ 83  79 103]
  [ 82  77 106]
  [ 72  69  99]]

 [[ 58  58  64]
  [ 61  59  66]
  [ 70  62  79]
  ...
  [ 85  74 109]
  [ 83  67 106]
  [ 79  62 108]]

 [[ 46  58  60]
  [ 56  61  65]
  [ 62  54  69]
  ...
  [ 86  76 104]
  [ 84  70 108]
  [ 89  70 118]]]
[[[209 193 182]
  [199 177 172]
  [202 175 176]
  ...
  [ 51  39  53]
  [ 48  37  48]
  [ 46  30  45]]

 [[197 181 175]
  [200 180 180]
  [194 170 176]
  ...
  [ 46  46  49]
  [ 48  44  46]
  [ 53  43  45]]

 [[194 174 179]
  [193 171 180]
  [203 177 190]
  ...
  [ 47  50  53]
  [ 44  45  44]
  [ 45  46  42]]

 ...

 [[ 56  60  75]
  [ 54  53  68]
  [ 66  58  70]
  ..

[[[202 175 171]
  [203 176 171]
  [202 174 173]
  ...
  [ 56  42  43]
  [ 59  37  39]
  [ 60  31  27]]

 [[202 177 177]
  [198 175 173]
  [196 177 177]
  ...
  [ 48  54  37]
  [ 43  39  30]
  [ 56  46  38]]

 [[205 174 179]
  [200 174 178]
  [198 182 184]
  ...
  [ 59  55  40]
  [ 57  44  33]
  [ 59  40  34]]

 ...

 [[ 58  55  79]
  [ 62  62  76]
  [ 65  62  69]
  ...
  [ 85  76 107]
  [ 79  78 102]
  [ 65  68  87]]

 [[ 64  48  66]
  [ 75  62  72]
  [ 72  63  68]
  ...
  [ 88  79 106]
  [ 84  83 104]
  [ 72  72  92]]

 [[ 64  64  76]
  [ 61  61  62]
  [ 65  65  59]
  ...
  [ 79  78  89]
  [ 77  81 100]
  [ 72  77 105]]]
[[[210 191 179]
  [209 180 173]
  [215 180 176]
  ...
  [ 58  25  57]
  [ 54  25  56]
  [ 56  36  54]]

 [[204 169 175]
  [202 165 171]
  [207 168 173]
  ...
  [ 48  40  37]
  [ 50  42  39]
  [ 49  39  36]]

 [[201 165 176]
  [200 166 175]
  [204 173 179]
  ...
  [ 39  47  19]
  [ 56  52  28]
  [ 56  45  23]]

 ...

 [[ 57  65  89]
  [ 48  50  73]
  [ 49  53  67]
  ..

[[[200 183 179]
  [204 185 177]
  [204 186 173]
  ...
  [ 38  36  37]
  [ 61  55  57]
  [ 49  43  43]]

 [[204 172 175]
  [200 172 167]
  [203 179 169]
  ...
  [ 38  47  45]
  [ 50  51  48]
  [ 53  48  41]]

 [[202 176 178]
  [200 177 175]
  [200 184 176]
  ...
  [ 46  52  56]
  [ 46  47  47]
  [ 51  45  38]]

 ...

 [[ 76  55  76]
  [ 76  58  73]
  [ 68  56  65]
  ...
  [ 84  67 108]
  [ 78  76 114]
  [ 63  78 107]]

 [[ 72  59  63]
  [ 68  57  61]
  [ 66  60  64]
  ...
  [ 84  65 113]
  [ 77  72 106]
  [ 76  81 103]]

 [[ 72  74  76]
  [ 72  75  74]
  [ 69  69  71]
  ...
  [ 90  78 109]
  [ 87  80 100]
  [ 84  85  93]]]
[[[213 185 196]
  [203 178 183]
  [204 181 181]
  ...
  [ 42  36  47]
  [ 58  39  53]
  [ 56  37  48]]

 [[197 174 172]
  [206 179 182]
  [207 179 184]
  ...
  [ 48  49  43]
  [ 48  48  43]
  [ 49  48  43]]

 [[201 175 177]
  [202 173 179]
  [199 170 178]
  ...
  [ 56  52  38]
  [ 59  49  38]
  [ 55  40  34]]

 ...

 [[ 40  63  75]
  [ 44  57  72]
  [ 54  53  74]
  ..

[[[202 182 182]
  [201 175 176]
  [204 177 175]
  ...
  [ 46  51  35]
  [ 49  47  37]
  [ 48  43  38]]

 [[194 186 173]
  [195 181 171]
  [200 179 174]
  ...
  [ 43  45  17]
  [ 51  39  19]
  [ 60  40  32]]

 [[195 184 175]
  [197 185 177]
  [197 177 175]
  ...
  [ 39  42  30]
  [ 53  44  38]
  [ 60  43  39]]

 ...

 [[ 48  70  87]
  [ 53  73  85]
  [ 48  61  70]
  ...
  [132 123 125]
  [124 115 117]
  [122 120 112]]

 [[ 41  59  66]
  [ 51  74  76]
  [ 47  69  73]
  ...
  [126 123 123]
  [122 119 121]
  [113 117 118]]

 [[ 47  76  80]
  [ 48  78  82]
  [ 36  68  74]
  ...
  [117 122 115]
  [111 124 117]
  [104 120 115]]]
[[[194 190 169]
  [186 180 165]
  [193 184 174]
  ...
  [ 53  46  46]
  [ 56  40  44]
  [ 63  34  36]]

 [[202 186 187]
  [196 178 179]
  [192 177 176]
  ...
  [ 46  40  31]
  [ 45  42  39]
  [ 44  41  42]]

 [[194 174 180]
  [193 175 179]
  [197 176 179]
  ...
  [ 48  55  46]
  [ 43  45  38]
  [ 51  52  45]]

 ...

 [[ 57  75  83]
  [ 46  57  69]
  [ 50  55  70]
  ..

[[[203 185 174]
  [204 179 173]
  [207 178 173]
  ...
  [ 45  53  42]
  [ 48  46  36]
  [ 47  37  38]]

 [[200 173 177]
  [203 176 178]
  [199 173 175]
  ...
  [ 48  57  42]
  [ 36  47  32]
  [ 40  48  41]]

 [[196 174 189]
  [196 169 185]
  [202 170 186]
  ...
  [ 39  49  46]
  [ 31  51  49]
  [ 35  61  59]]

 ...

 [[ 59  54  80]
  [ 60  54  77]
  [ 56  55  71]
  ...
  [ 78  58  96]
  [ 85  70 108]
  [ 73  67 102]]

 [[ 61  43  65]
  [ 75  63  83]
  [ 71  61  83]
  ...
  [ 72  57  99]
  [ 83  69 109]
  [ 71  65 101]]

 [[ 89  55  76]
  [ 85  52  75]
  [ 72  44  70]
  ...
  [ 85  69 101]
  [ 75  65  94]
  [ 91  87 113]]]
[[[204 176 179]
  [206 179 180]
  [199 179 178]
  ...
  [ 58  48  33]
  [ 64  41  35]
  [ 70  37  40]]

 [[203 179 180]
  [199 173 175]
  [201 176 175]
  ...
  [ 48  48  42]
  [ 48  40  35]
  [ 56  42  39]]

 [[201 177 177]
  [198 174 175]
  [201 175 177]
  ...
  [ 44  44  44]
  [ 50  38  39]
  [ 55  38  40]]

 ...

 [[ 49  57  55]
  [ 55  59  59]
  [ 63  60  62]
  ..

[[[199 196 158]
  [200 186 159]
  [198 171 159]
  ...
  [ 50  54  45]
  [ 53  48  40]
  [ 57  35  36]]

 [[200 184 170]
  [202 184 171]
  [204 182 177]
  ...
  [ 42  54  44]
  [ 41  45  46]
  [ 44  40  49]]

 [[203 179 181]
  [195 174 173]
  [202 183 177]
  ...
  [ 39  45  53]
  [ 44  40  52]
  [ 51  45  55]]

 ...

 [[ 49  66  85]
  [ 53  55  79]
  [ 65  53  74]
  ...
  [ 86  69 108]
  [ 80  65 106]
  [ 67  50  95]]

 [[ 65  67  71]
  [ 63  69  74]
  [ 60  65  79]
  ...
  [ 82  68  94]
  [ 82  71 101]
  [ 78  73 105]]

 [[ 53  73  67]
  [ 57  76  69]
  [ 50  62  67]
  ...
  [ 81  73  93]
  [ 75  71  86]
  [ 90  86  99]]]
[[[197 183 184]
  [196 179 182]
  [200 180 185]
  ...
  [ 63  53  56]
  [ 60  43  40]
  [ 61  30  27]]

 [[205 172 187]
  [202 176 184]
  [197 178 180]
  ...
  [ 55  51  41]
  [ 57  44  32]
  [ 60  41  32]]

 [[199 163 169]
  [200 171 173]
  [199 178 176]
  ...
  [ 53  50  39]
  [ 59  52  36]
  [ 53  46  30]]

 ...

 [[ 64  56  63]
  [ 71  55  70]
  [ 73  52  73]
  ..

[[[208 190 170]
  [205 180 173]
  [207 176 183]
  ...
  [ 44  49  48]
  [ 36  44  52]
  [ 34  41  55]]

 [[203 180 183]
  [205 174 180]
  [202 169 176]
  ...
  [ 49  55  42]
  [ 43  50  42]
  [ 42  44  47]]

 [[208 178 187]
  [202 174 182]
  [199 175 182]
  ...
  [ 44  56  41]
  [ 41  53  37]
  [ 44  51  39]]

 ...

 [[ 57  71  56]
  [ 57  64  56]
  [ 54  57  60]
  ...
  [ 79  69 108]
  [ 87  67 114]
  [ 71  50 101]]

 [[ 62  69  52]
  [ 64  70  60]
  [ 60  62  67]
  ...
  [ 76  65 104]
  [ 86  73 113]
  [ 78  68 107]]

 [[ 68  57  52]
  [ 70  61  60]
  [ 69  64  71]
  ...
  [ 77  71 101]
  [ 84  75 104]
  [ 77  71  93]]]
[[[207 179 187]
  [204 168 177]
  [206 167 176]
  ...
  [ 50  55  51]
  [ 49  42  39]
  [ 53  42  35]]

 [[205 180 188]
  [202 178 184]
  [195 173 177]
  ...
  [ 58  54  40]
  [ 59  48  31]
  [ 59  42  29]]

 [[204 163 181]
  [208 171 183]
  [209 177 182]
  ...
  [ 53  50  44]
  [ 55  46  37]
  [ 58  47  39]]

 ...

 [[ 55  67  62]
  [ 53  68  67]
  [ 56  63  75]
  ..

[[[193 180 178]
  [196 180 179]
  [201 175 175]
  ...
  [ 43  51  35]
  [ 46  53  47]
  [ 38  37  39]]

 [[195 177 171]
  [195 175 172]
  [199 176 179]
  ...
  [ 39  47  32]
  [ 45  43  38]
  [ 49  40  46]]

 [[201 179 177]
  [196 173 171]
  [202 178 177]
  ...
  [ 41  51  44]
  [ 44  43  38]
  [ 49  42  41]]

 ...

 [[ 58  67  58]
  [ 61  62  63]
  [ 65  57  74]
  ...
  [ 76  63 109]
  [ 81  64 110]
  [ 70  52  97]]

 [[ 58  67  63]
  [ 61  63  65]
  [ 63  57  73]
  ...
  [ 76  75 107]
  [ 81  77 114]
  [ 79  70 109]]

 [[ 61  66  66]
  [ 64  64  66]
  [ 67  59  68]
  ...
  [ 78  77 119]
  [ 71  75 117]
  [ 76  83 123]]]
[[[188 188 181]
  [194 179 178]
  [204 174 181]
  ...
  [ 48  50  41]
  [ 46  49  45]
  [ 44  49  47]]

 [[198 174 175]
  [207 177 179]
  [209 172 179]
  ...
  [ 59  48  43]
  [ 50  44  36]
  [ 56  52  46]]

 [[203 168 175]
  [208 173 176]
  [208 177 179]
  ...
  [ 59  43  55]
  [ 49  33  40]
  [ 65  51  50]]

 ...

 [[ 64  58  70]
  [ 61  51  66]
  [ 60  52  69]
  ..

[[[211 186 167]
  [217 178 173]
  [220 173 178]
  ...
  [ 68  43  34]
  [ 54  35  28]
  [ 46  36  35]]

 [[213 178 170]
  [212 176 172]
  [208 176 176]
  ...
  [ 57  44  38]
  [ 57  49  45]
  [ 59  47  51]]

 [[206 180 187]
  [200 175 179]
  [201 179 180]
  ...
  [ 51  49  42]
  [ 55  46  47]
  [ 59  47  55]]

 ...

 [[ 60  62  71]
  [ 64  59  71]
  [ 55  48  66]
  ...
  [ 92  67 100]
  [ 86  61  94]
  [ 85  67  96]]

 [[ 66  65  70]
  [ 73  62  78]
  [ 67  51  79]
  ...
  [ 84  76  99]
  [ 88  71  97]
  [ 75  57  86]]

 [[ 68  57  85]
  [ 72  55  87]
  [ 63  54  81]
  ...
  [ 82  82 102]
  [ 82  75 107]
  [ 82  71 114]]]
[[[206 181 188]
  [191 168 171]
  [209 188 187]
  ...
  [ 60  36  39]
  [ 65  36  40]
  [ 61  36  40]]

 [[204 173 176]
  [196 168 171]
  [204 181 181]
  ...
  [ 46  39  30]
  [ 57  37  37]
  [ 62  35  40]]

 [[204 176 174]
  [205 174 178]
  [206 177 181]
  ...
  [ 52  52  50]
  [ 48  35  37]
  [ 59  38  38]]

 ...

 [[ 66  57  85]
  [ 60  49  76]
  [ 57  42  70]
  ..

[[[199 177 176]
  [202 179 179]
  [203 182 182]
  ...
  [ 39  36  36]
  [ 57  45  47]
  [ 53  38  43]]

 [[201 183 172]
  [205 185 176]
  [205 183 182]
  ...
  [ 53  45  51]
  [ 50  42  48]
  [ 58  48  54]]

 [[204 189 180]
  [202 179 174]
  [201 178 179]
  ...
  [ 40  53  50]
  [ 43  44  51]
  [ 54  39  55]]

 ...

 [[ 52  70  69]
  [ 49  64  66]
  [ 48  67  71]
  ...
  [ 85  71  99]
  [ 80  70  99]
  [ 75  66  95]]

 [[ 55  58  64]
  [ 59  63  70]
  [ 62  63  75]
  ...
  [ 88  64  97]
  [ 88  72 101]
  [ 80  71  95]]

 [[ 76  65  87]
  [ 74  59  83]
  [ 72  54  77]
  ...
  [ 77  72  93]
  [ 73  74  88]
  [ 76  79  92]]]
[[[227 171 176]
  [215 163 173]
  [210 166 181]
  ...
  [ 50  46  42]
  [ 50  38  40]
  [ 54  34  41]]

 [[206 172 178]
  [200 168 176]
  [207 178 190]
  ...
  [ 45  47  43]
  [ 49  37  40]
  [ 65  37  49]]

 [[200 179 177]
  [191 172 175]
  [200 181 186]
  ...
  [ 40  50  46]
  [ 48  46  47]
  [ 50  43  48]]

 ...

 [[ 54  67  81]
  [ 53  61  73]
  [ 50  59  68]
  ..

[[[198 193 170]
  [195 185 169]
  [204 182 174]
  ...
  [ 50  44  54]
  [ 55  45  52]
  [ 52  40  51]]

 [[202 192 178]
  [200 189 172]
  [197 179 167]
  ...
  [ 48  46  36]
  [ 47  43  35]
  [ 60  46  48]]

 [[196 175 178]
  [198 178 179]
  [194 180 172]
  ...
  [ 42  46  39]
  [ 46  47  35]
  [ 45  45  30]]

 ...

 [[ 64  58  82]
  [ 59  57  72]
  [ 62  65  72]
  ...
  [ 81  73  98]
  [ 78  74  91]
  [ 72  70  82]]

 [[ 62  58  83]
  [ 69  65  89]
  [ 77  70  89]
  ...
  [ 83  70 110]
  [ 78  68 100]
  [ 77  71  96]]

 [[ 78  51  99]
  [ 73  50  90]
  [ 84  60  89]
  ...
  [ 80  65  99]
  [ 81  63 101]
  [ 84  69 106]]]
[[[209 180 183]
  [213 175 182]
  [209 165 180]
  ...
  [ 46  48  47]
  [ 39  50  45]
  [ 31  44  47]]

 [[208 172 180]
  [206 171 174]
  [205 174 173]
  ...
  [ 38  51  44]
  [ 34  48  45]
  [ 38  52  52]]

 [[209 174 171]
  [202 169 167]
  [201 177 169]
  ...
  [ 39  48  46]
  [ 39  45  42]
  [ 50  49  48]]

 ...

 [[ 76  65  72]
  [ 65  56  68]
  [ 61  53  76]
  ..

[[[215 180 180]
  [210 173 177]
  [206 174 179]
  ...
  [ 59  45  46]
  [ 53  41  44]
  [ 53  31  45]]

 [[201 175 166]
  [201 178 173]
  [202 180 182]
  ...
  [ 54  44  41]
  [ 50  40  39]
  [ 58  43  45]]

 [[193 173 164]
  [198 179 172]
  [202 180 180]
  ...
  [ 59  44  45]
  [ 56  39  45]
  [ 52  39  46]]

 ...

 [[ 57  68  74]
  [ 63  69  75]
  [ 64  65  75]
  ...
  [ 73  82 111]
  [ 72  78 107]
  [ 64  65  95]]

 [[ 63  67  69]
  [ 65  71  70]
  [ 66  72  73]
  ...
  [ 84  74  96]
  [ 84  80 103]
  [ 72  75  96]]

 [[ 64  59  77]
  [ 73  73  80]
  [ 75  75  76]
  ...
  [ 84  63  72]
  [ 87  67  76]
  [ 79  68  73]]]
[[[190 189 182]
  [195 186 180]
  [193 177 177]
  ...
  [ 66  47  46]
  [ 60  43  36]
  [ 55  49  34]]

 [[195 179 178]
  [198 179 180]
  [200 176 180]
  ...
  [ 54  47  38]
  [ 53  44  33]
  [ 61  50  38]]

 [[202 173 173]
  [197 169 171]
  [201 177 179]
  ...
  [ 39  48  36]
  [ 43  38  24]
  [ 59  43  28]]

 ...

 [[ 90  86  90]
  [120 116 119]
  [147 145 142]
  ..

[[[197 186 172]
  [197 185 170]
  [208 189 180]
  ...
  [ 64  40  40]
  [ 55  52  33]
  [ 48  55  33]]

 [[204 181 174]
  [202 178 174]
  [201 177 178]
  ...
  [ 46  40  36]
  [ 45  44  37]
  [ 54  48  46]]

 [[203 180 167]
  [196 176 165]
  [198 180 176]
  ...
  [ 43  48  55]
  [ 53  49  58]
  [ 61  45  54]]

 ...

 [[ 81  86 109]
  [ 73  81  98]
  [ 67  79  89]
  ...
  [ 85  75 106]
  [ 81  72 102]
  [ 77  68  98]]

 [[ 79  69  72]
  [ 74  75  79]
  [ 70  82  86]
  ...
  [ 77  73 104]
  [ 77  72  98]
  [ 75  67  91]]

 [[ 82  66  69]
  [ 77  71  72]
  [ 77  81  89]
  ...
  [ 78  84 109]
  [ 73  86  99]
  [ 79  89  97]]]
[[[210 192 184]
  [200 174 172]
  [214 178 181]
  ...
  [ 65  37  34]
  [ 60  43  33]
  [ 49  38  26]]

 [[215 180 179]
  [212 175 172]
  [212 177 171]
  ...
  [ 56  44  36]
  [ 54  43  35]
  [ 52  41  34]]

 [[207 176 175]
  [207 175 172]
  [206 176 169]
  ...
  [ 48  42  46]
  [ 55  39  48]
  [ 52  37  45]]

 ...

 [[ 76  80  91]
  [ 81  81  91]
  [ 78  78  86]
  ..

[[[191 190 174]
  [189 184 175]
  [196 184 182]
  ...
  [ 52  45  54]
  [ 45  39  49]
  [ 37  33  39]]

 [[199 181 173]
  [192 172 166]
  [198 177 173]
  ...
  [ 55  48  50]
  [ 50  46  43]
  [ 54  50  43]]

 [[198 173 169]
  [196 175 168]
  [188 172 164]
  ...
  [ 53  44  37]
  [ 50  44  31]
  [ 58  52  36]]

 ...

 [[109  84 104]
  [137 111 128]
  [158 139 143]
  ...
  [ 92  76  99]
  [ 92  80 106]
  [ 78  65  96]]

 [[139 111 121]
  [158 134 140]
  [183 168 168]
  ...
  [ 82  66  94]
  [ 89  69  97]
  [ 90  69  95]]

 [[160 136 125]
  [178 158 145]
  [200 182 176]
  ...
  [ 84  65  88]
  [ 89  65  89]
  [ 98  75  98]]]
[[[207 184 182]
  [202 173 175]
  [213 179 184]
  ...
  [ 42  45  45]
  [ 47  37  46]
  [ 57  29  55]]

 [[203 171 168]
  [205 175 172]
  [203 176 175]
  ...
  [ 44  46  46]
  [ 48  36  42]
  [ 66  34  52]]

 [[203 170 164]
  [207 176 173]
  [203 175 173]
  ...
  [ 43  48  45]
  [ 50  40  43]
  [ 65  40  49]]

 ...

 [[ 76  85  87]
  [ 69  74  71]
  [ 78  73  68]
  ..

[[[212 184 156]
  [204 184 163]
  [199 186 176]
  ...
  [ 59  39  35]
  [ 64  36  36]
  [ 71  39  40]]

 [[206 182 164]
  [202 183 167]
  [200 181 171]
  ...
  [ 47  54  39]
  [ 45  49  34]
  [ 56  50  37]]

 [[199 170 166]
  [200 175 168]
  [199 180 169]
  ...
  [ 43  47  29]
  [ 49  46  25]
  [ 59  54  30]]

 ...

 [[ 57  63  66]
  [ 62  64  68]
  [ 63  60  68]
  ...
  [ 76  69 108]
  [ 78  85 112]
  [ 53  75  95]]

 [[ 53  54  49]
  [ 62  65  61]
  [ 62  63  64]
  ...
  [ 72  65 105]
  [ 79  82 110]
  [ 71  78  99]]

 [[ 64  68  71]
  [ 71  68  76]
  [ 69  61  71]
  ...
  [ 82  73 107]
  [ 83  69 110]
  [ 80  67 106]]]
[[[199 188 160]
  [207 184 169]
  [205 171 174]
  ...
  [ 47  41  50]
  [ 56  39  55]
  [ 58  35  54]]

 [[199 187 178]
  [198 182 175]
  [198 177 177]
  ...
  [ 38  37  31]
  [ 44  35  35]
  [ 56  41  44]]

 [[199 181 182]
  [192 174 177]
  [191 176 179]
  ...
  [ 39  48  31]
  [ 44  45  35]
  [ 45  48  40]]

 ...

 [[ 62  67  74]
  [ 65  69  73]
  [ 63  63  68]
  ..

[[[209 183 171]
  [210 182 175]
  [209 180 178]
  ...
  [ 42  41  53]
  [ 53  39  63]
  [ 49  32  60]]

 [[203 178 169]
  [204 178 172]
  [199 178 175]
  ...
  [ 40  51  45]
  [ 41  42  44]
  [ 47  42  50]]

 [[206 176 170]
  [209 178 173]
  [206 175 176]
  ...
  [ 49  47  41]
  [ 48  43  29]
  [ 62  50  27]]

 ...

 [[ 65  77  71]
  [ 63  65  61]
  [ 60  65  60]
  ...
  [ 68  76 111]
  [ 68  76 114]
  [ 60  66 104]]

 [[ 63  62  72]
  [ 65  65  72]
  [ 61  70  69]
  ...
  [ 74  69 108]
  [ 76  73 109]
  [ 70  68 103]]

 [[ 76  68  69]
  [ 70  66  68]
  [ 64  66  68]
  ...
  [ 81  72  88]
  [ 84  74  85]
  [ 87  73  92]]]
[[[205 182 173]
  [205 176 169]
  [205 176 173]
  ...
  [ 54  40  37]
  [ 64  41  30]
  [ 62  28  21]]

 [[196 178 170]
  [198 176 172]
  [199 176 177]
  ...
  [ 54  42  45]
  [ 61  38  38]
  [ 57  30  29]]

 [[197 178 187]
  [191 170 179]
  [195 175 185]
  ...
  [ 48  50  50]
  [ 40  39  29]
  [ 41  39  19]]

 ...

 [[ 63  62  87]
  [ 53  58  73]
  [ 56  65  70]
  ..

[[[204 186 170]
  [199 181 167]
  [196 182 172]
  ...
  [ 66  34  36]
  [ 58  38  29]
  [ 54  48  37]]

 [[196 192 167]
  [193 183 163]
  [194 179 170]
  ...
  [ 61  40  38]
  [ 53  36  28]
  [ 62  48  44]]

 [[197 181 168]
  [194 176 167]
  [198 176 172]
  ...
  [ 59  46  41]
  [ 49  39  35]
  [ 57  47  46]]

 ...

 [[ 70  56  79]
  [ 67  54  76]
  [ 64  54  70]
  ...
  [ 81  80 114]
  [ 82  78 113]
  [ 66  66  96]]

 [[ 63  58  80]
  [ 65  63  77]
  [ 65  66  74]
  ...
  [ 68  65  87]
  [ 78  74  93]
  [ 78  77  93]]

 [[ 70  62  83]
  [ 70  67  81]
  [ 60  70  69]
  ...
  [ 83  75  93]
  [ 74  64  86]
  [101  89 112]]]
[[[186 177 175]
  [194 179 180]
  [198 182 186]
  ...
  [ 52  51  45]
  [ 49  35  32]
  [ 57  37  41]]

 [[203 180 174]
  [199 175 172]
  [207 179 183]
  ...
  [ 43  53  45]
  [ 41  39  31]
  [ 62  45  41]]

 [[198 175 171]
  [199 176 171]
  [202 178 175]
  ...
  [ 32  62  44]
  [ 37  53  34]
  [ 49  47  32]]

 ...

 [[ 73  69  80]
  [ 70  63  77]
  [ 72  57  79]
  ..

[[[197 189 172]
  [201 186 173]
  [201 181 174]
  ...
  [ 36  45  45]
  [ 36  47  45]
  [ 38  44  43]]

 [[182 175 161]
  [194 183 169]
  [192 180 167]
  ...
  [ 49  49  43]
  [ 46  46  33]
  [ 52  47  34]]

 [[192 182 169]
  [195 179 170]
  [191 173 168]
  ...
  [ 43  41  40]
  [ 52  42  34]
  [ 54  42  33]]

 ...

 [[ 79  60  85]
  [ 82  61  86]
  [ 67  47  68]
  ...
  [ 77  64  97]
  [ 82  69 115]
  [ 65  61 115]]

 [[ 66  56  88]
  [ 66  57  90]
  [ 68  57  89]
  ...
  [ 74  64 101]
  [ 76  63  99]
  [ 77  62  94]]

 [[ 61  77  94]
  [ 62  70  87]
  [ 58  57  73]
  ...
  [ 70  70 106]
  [ 71  68  89]
  [ 83  77  80]]]
[[[194 175 187]
  [195 175 182]
  [191 177 175]
  ...
  [ 54  44  37]
  [ 49  40  24]
  [ 55  49  28]]

 [[193 178 177]
  [195 177 176]
  [192 176 173]
  ...
  [ 54  48  29]
  [ 42  43  19]
  [ 50  53  27]]

 [[189 175 177]
  [194 175 175]
  [200 178 177]
  ...
  [ 48  57  40]
  [ 45  44  28]
  [ 65  50  35]]

 ...

 [[ 53  59  77]
  [ 62  63  75]
  [ 67  63  69]
  ..

[[[194 186 190]
  [192 182 183]
  [195 178 181]
  ...
  [ 51  45  56]
  [ 50  33  58]
  [ 54  25  61]]

 [[192 174 183]
  [196 176 183]
  [196 174 179]
  ...
  [ 45  45  43]
  [ 49  38  43]
  [ 59  42  54]]

 [[202 179 183]
  [201 177 181]
  [198 176 178]
  ...
  [ 45  48  44]
  [ 48  43  37]
  [ 57  46  40]]

 ...

 [[ 66  68  73]
  [ 66  66  72]
  [ 73  63  75]
  ...
  [ 72  77  98]
  [ 83  81 111]
  [ 71  62  97]]

 [[ 68  66  51]
  [ 68  64  55]
  [ 77  66  62]
  ...
  [ 70  80  98]
  [ 80  78 106]
  [ 73  64  94]]

 [[ 80  77  68]
  [ 68  64  56]
  [ 72  67  56]
  ...
  [ 81  88 106]
  [ 82  80 109]
  [ 82  73 103]]]
[[[202 179 178]
  [201 175 174]
  [206 172 177]
  ...
  [ 69  47  32]
  [ 61  47  30]
  [ 47  39  27]]

 [[203 177 175]
  [200 175 173]
  [207 181 177]
  ...
  [ 55  55  38]
  [ 48  52  30]
  [ 46  47  30]]

 [[205 179 184]
  [196 168 172]
  [207 175 176]
  ...
  [ 47  44  27]
  [ 50  50  32]
  [ 52  54  33]]

 ...

 [[ 70  66  80]
  [ 65  62  74]
  [ 57  60  68]
  ..

[[[210 187 182]
  [198 177 172]
  [201 183 176]
  ...
  [ 53  46  56]
  [ 43  38  48]
  [ 44  38  54]]

 [[199 168 158]
  [201 177 167]
  [200 183 174]
  ...
  [ 49  54  50]
  [ 47  48  37]
  [ 50  43  33]]

 [[199 176 169]
  [195 173 167]
  [199 179 176]
  ...
  [ 48  49  51]
  [ 44  45  32]
  [ 46  45  20]]

 ...

 [[ 41  66  69]
  [ 47  63  72]
  [ 47  60  72]
  ...
  [ 90  76 107]
  [ 83  71 101]
  [ 78  62  91]]

 [[ 59  64  70]
  [ 56  61  68]
  [ 60  63  72]
  ...
  [ 86  78 103]
  [ 89  77  97]
  [ 85  68  85]]

 [[ 65  56  74]
  [ 66  56  73]
  [ 67  55  66]
  ...
  [ 84  78  92]
  [ 91  79  95]
  [ 94  76  94]]]
[[[203 183 163]
  [206 181 172]
  [197 175 178]
  ...
  [ 51  47  38]
  [ 52  41  34]
  [ 58  43  42]]

 [[199 177 172]
  [199 178 175]
  [197 178 180]
  ...
  [ 51  43  48]
  [ 54  33  38]
  [ 63  35  43]]

 [[195 177 170]
  [195 178 173]
  [195 178 176]
  ...
  [ 45  41  44]
  [ 57  35  38]
  [ 57  30  26]]

 ...

 [[ 67  59  76]
  [ 63  49  68]
  [ 71  51  71]
  ..

[[[212 169 165]
  [219 183 183]
  [210 182 189]
  ...
  [ 57  41  42]
  [ 67  48  49]
  [ 64  37  48]]

 [[202 165 178]
  [205 167 180]
  [208 175 187]
  ...
  [ 55  48  41]
  [ 48  40  32]
  [ 55  45  39]]

 [[187 181 182]
  [192 180 181]
  [194 178 178]
  ...
  [ 48  56  35]
  [ 53  47  34]
  [ 60  43  38]]

 ...

 [[ 56  66  73]
  [ 62  58  73]
  [ 74  53  78]
  ...
  [ 83  76 103]
  [ 86  71  95]
  [ 90  74  97]]

 [[ 65  57  62]
  [ 66  62  70]
  [ 64  52  74]
  ...
  [ 85  72 100]
  [ 84  74  90]
  [ 85  78  90]]

 [[ 69  60  75]
  [ 67  65  79]
  [ 60  55  80]
  ...
  [ 82  71  91]
  [ 83  78  89]
  [ 91  89  92]]]
[[[208 183 188]
  [197 177 180]
  [197 181 184]
  ...
  [ 53  40  40]
  [ 68  38  40]
  [ 67  30  39]]

 [[202 171 179]
  [205 176 180]
  [203 175 177]
  ...
  [ 41  49  45]
  [ 43  43  38]
  [ 43  40  30]]

 [[197 174 184]
  [198 175 181]
  [200 177 177]
  ...
  [ 46  60  61]
  [ 50  52  50]
  [ 47  44  35]]

 ...

 [[ 50  67  65]
  [ 55  70  67]
  [ 53  63  59]
  ..

[[[206 174 177]
  [203 178 180]
  [196 177 178]
  ...
  [ 47  37  56]
  [ 47  38  52]
  [ 53  39  49]]

 [[208 174 166]
  [202 175 170]
  [205 180 180]
  ...
  [ 47  49  46]
  [ 40  43  31]
  [ 53  58  39]]

 [[199 174 162]
  [199 176 165]
  [206 184 175]
  ...
  [ 43  52  44]
  [ 46  50  31]
  [ 54  52  23]]

 ...

 [[ 71  60  62]
  [ 71  60  66]
  [ 64  52  67]
  ...
  [ 88  74 109]
  [ 84  70 110]
  [ 71  62  99]]

 [[ 49  62  47]
  [ 56  65  60]
  [ 55  59  66]
  ...
  [ 86  75 100]
  [ 89  76 107]
  [ 77  62  93]]

 [[ 57  67  58]
  [ 63  70  61]
  [ 57  65  65]
  ...
  [ 84  80  94]
  [ 79  74  95]
  [ 88  77 102]]]
[[[205 187 180]
  [198 181 176]
  [198 182 182]
  ...
  [ 49  48  54]
  [ 41  55  44]
  [ 34  55  30]]

 [[199 181 169]
  [197 181 172]
  [197 184 180]
  ...
  [ 58  47  54]
  [ 46  39  36]
  [ 53  51  40]]

 [[193 177 168]
  [198 180 174]
  [202 182 183]
  ...
  [ 49  46  46]
  [ 43  41  41]
  [ 47  45  46]]

 ...

 [[ 68  57  57]
  [ 72  62  65]
  [ 69  60  72]
  ..

[[[194 184 184]
  [196 181 184]
  [198 180 182]
  ...
  [ 44  53  56]
  [ 44  49  46]
  [ 44  48  43]]

 [[196 180 183]
  [198 181 185]
  [195 177 181]
  ...
  [ 47  49  48]
  [ 35  43  40]
  [ 35  50  46]]

 [[192 174 176]
  [195 179 178]
  [196 182 178]
  ...
  [ 41  51  47]
  [ 46  48  45]
  [ 49  51  45]]

 ...

 [[ 55  63  69]
  [ 57  62  71]
  [ 62  61  67]
  ...
  [ 81  78  99]
  [ 76  79 104]
  [ 63  71 101]]

 [[ 54  55  68]
  [ 60  62  76]
  [ 62  59  79]
  ...
  [ 81  75 100]
  [ 81  76 103]
  [ 77  77 102]]

 [[ 61  62  69]
  [ 63  64  73]
  [ 58  56  80]
  ...
  [ 90  78  97]
  [ 98  74  96]
  [100  75  91]]]
[[[190 184 183]
  [197 183 183]
  [201 178 176]
  ...
  [ 49  52  48]
  [ 52  46  54]
  [ 52  42  57]]

 [[199 184 180]
  [199 178 179]
  [207 177 181]
  ...
  [ 47  51  34]
  [ 46  46  37]
  [ 50  49  48]]

 [[195 173 170]
  [199 176 177]
  [201 178 179]
  ...
  [ 44  47  36]
  [ 37  42  31]
  [ 47  52  44]]

 ...

 [[ 68  61  74]
  [ 64  55  73]
  [ 65  53  68]
  ..

[[[196 195 186]
  [190 180 173]
  [193 175 172]
  ...
  [ 49  52  42]
  [ 49  49  40]
  [ 49  47  36]]

 [[199 175 175]
  [201 176 174]
  [194 175 172]
  ...
  [ 43  51  28]
  [ 37  49  26]
  [ 33  54  31]]

 [[200 169 165]
  [201 172 170]
  [204 177 179]
  ...
  [ 42  52  25]
  [ 37  51  23]
  [ 35  57  27]]

 ...

 [[ 55  60  80]
  [ 57  63  81]
  [ 53  59  78]
  ...
  [ 90  74  90]
  [ 84  74  93]
  [ 71  71  91]]

 [[ 39  64  69]
  [ 50  68  72]
  [ 57  65  72]
  ...
  [ 80  70  91]
  [ 80  74  96]
  [ 68  76  93]]

 [[ 46  76  93]
  [ 53  73  81]
  [ 57  68  65]
  ...
  [ 84  76  88]
  [ 77  77  93]
  [ 70  82  99]]]
[[[210 179 186]
  [208 178 185]
  [205 176 183]
  ...
  [ 47  45  61]
  [ 54  48  56]
  [ 50  40  44]]

 [[203 176 179]
  [195 172 172]
  [201 178 179]
  ...
  [ 45  42  37]
  [ 46  49  34]
  [ 47  48  34]]

 [[198 177 178]
  [196 175 176]
  [193 175 177]
  ...
  [ 50  45  40]
  [ 46  46  31]
  [ 46  52  31]]

 ...

 [[ 68  60  81]
  [ 66  57  81]
  [ 59  50  77]
  ..

[[[217 179 176]
  [209 177 171]
  [209 184 176]
  ...
  [ 55  55  50]
  [ 41  43  51]
  [ 31  36  48]]

 [[214 174 177]
  [210 176 175]
  [204 180 171]
  ...
  [ 56  52  43]
  [ 52  44  39]
  [ 56  47  44]]

 [[202 174 169]
  [198 172 173]
  [198 177 179]
  ...
  [ 48  47  41]
  [ 55  43  33]
  [ 58  38  30]]

 ...

 [[ 68  36  76]
  [ 60  35  65]
  [ 68  54  70]
  ...
  [ 87  73  95]
  [ 92  69  98]
  [ 79  50  86]]

 [[ 61  52  78]
  [ 66  67  82]
  [ 63  72  81]
  ...
  [ 79  71  91]
  [ 82  76  95]
  [ 82  75  95]]

 [[ 51  74  82]
  [ 52  72  77]
  [ 49  70  69]
  ...
  [ 78  72 108]
  [ 81  75 109]
  [ 77  70 106]]]
[[[210 185 174]
  [212 181 176]
  [208 172 175]
  ...
  [ 44  49  35]
  [ 56  44  33]
  [ 64  37  32]]

 [[200 178 178]
  [205 178 178]
  [210 178 180]
  ...
  [ 47  53  46]
  [ 48  51  42]
  [ 56  53  45]]

 [[199 178 183]
  [200 177 179]
  [201 176 175]
  ...
  [ 41  51  53]
  [ 39  46  43]
  [ 47  56  45]]

 ...

 [[ 55  61  78]
  [ 61  60  76]
  [ 61  54  72]
  ..

[[[190 189 182]
  [196 191 183]
  [191 183 175]
  ...
  [ 44  41  34]
  [ 38  47  43]
  [ 24  37  37]]

 [[188 188 167]
  [196 188 172]
  [193 178 167]
  ...
  [ 46  45  39]
  [ 45  43  43]
  [ 45  46  50]]

 [[203 182 171]
  [200 178 168]
  [197 174 171]
  ...
  [ 54  48  42]
  [ 57  47  45]
  [ 51  49  49]]

 ...

 [[ 55  57  72]
  [ 64  57  80]
  [ 68  52  81]
  ...
  [ 90  76 104]
  [ 84  75 107]
  [ 69  67  95]]

 [[ 51  64  77]
  [ 56  69  83]
  [ 62  63  83]
  ...
  [ 78  70  95]
  [ 80  76 101]
  [ 67  71  93]]

 [[ 53  79  96]
  [ 52  67  87]
  [ 62  61  77]
  ...
  [ 87  77 116]
  [ 83  71 109]
  [ 86  72 109]]]
[[[203 188 158]
  [203 184 161]
  [206 185 179]
  ...
  [ 49  45  47]
  [ 45  45  40]
  [ 48  41  36]]

 [[198 179 169]
  [202 181 173]
  [204 183 178]
  ...
  [ 46  50  45]
  [ 47  39  40]
  [ 54  33  42]]

 [[195 175 177]
  [200 177 179]
  [198 177 175]
  ...
  [ 47  43  51]
  [ 52  41  46]
  [ 58  38  39]]

 ...

 [[ 63  59  75]
  [ 64  55  73]
  [ 65  50  71]
  ..

[[[211 178 182]
  [208 174 179]
  [208 172 181]
  ...
  [ 58  49  42]
  [ 62  41  38]
  [ 61  40  41]]

 [[206 175 183]
  [202 173 180]
  [203 177 182]
  ...
  [ 56  45  28]
  [ 60  42  29]
  [ 63  45  36]]

 [[194 169 179]
  [195 172 179]
  [195 174 178]
  ...
  [ 68  49  41]
  [ 69  44  41]
  [ 69  43  38]]

 ...

 [[ 58  56  59]
  [ 60  65  68]
  [ 49  61  68]
  ...
  [ 79  69  98]
  [ 91  69 105]
  [ 87  57  94]]

 [[ 48  61  58]
  [ 51  69  66]
  [ 44  68  69]
  ...
  [ 78  69 105]
  [ 88  70 106]
  [ 80  59  87]]

 [[ 61  75  83]
  [ 53  68  77]
  [ 51  67  78]
  ...
  [ 81  71 102]
  [ 86  77 101]
  [ 86  81 102]]]
[[[208 185 191]
  [196 174 177]
  [207 180 179]
  ...
  [ 63  40  62]
  [ 62  33  56]
  [ 64  31  50]]

 [[202 176 168]
  [197 171 166]
  [205 173 174]
  ...
  [ 45  47  39]
  [ 47  39  40]
  [ 49  33  40]]

 [[188 178 174]
  [189 178 173]
  [194 180 177]
  ...
  [ 49  53  50]
  [ 40  45  38]
  [ 40  44  34]]

 ...

 [[ 56  68  86]
  [ 59  64  80]
  [ 58  60  71]
  ..

[[[188 179 172]
  [194 180 173]
  [203 182 182]
  ...
  [ 41  50  47]
  [ 49  47  46]
  [ 48  41  42]]

 [[210 180 180]
  [206 177 176]
  [207 182 179]
  ...
  [ 50  42  50]
  [ 48  43  47]
  [ 44  43  46]]

 [[208 183 168]
  [207 179 166]
  [209 179 169]
  ...
  [ 40  37  45]
  [ 51  40  43]
  [ 55  37  38]]

 ...

 [[ 70  48  77]
  [ 67  52  76]
  [ 62  58  78]
  ...
  [ 86  83 104]
  [ 88  83 107]
  [ 69  63  88]]

 [[ 59  52  77]
  [ 57  59  80]
  [ 54  66  81]
  ...
  [ 86  78  98]
  [ 87  82  99]
  [ 78  75  95]]

 [[ 53  57  93]
  [ 54  61  93]
  [ 47  62  82]
  ...
  [ 87  77 104]
  [ 81  76  93]
  [ 87  85  98]]]
[[[209 189 182]
  [199 178 175]
  [202 177 183]
  ...
  [ 48  45  50]
  [ 60  37  40]
  [ 68  26  34]]

 [[203 177 173]
  [200 173 171]
  [200 171 171]
  ...
  [ 45  46  45]
  [ 40  38  38]
  [ 45  39  44]]

 [[200 181 167]
  [197 177 167]
  [191 174 168]
  ...
  [ 40  45  47]
  [ 38  45  47]
  [ 40  53  51]]

 ...

 [[ 42  74  75]
  [ 47  73  77]
  [ 48  63  76]
  ..

[[[209 187 178]
  [206 180 172]
  [212 186 180]
  ...
  [ 50  45  28]
  [ 59  51  36]
  [ 56  47  39]]

 [[200 180 172]
  [197 180 172]
  [196 184 171]
  ...
  [ 50  56  29]
  [ 48  47  24]
  [ 47  38  21]]

 [[194 176 179]
  [191 173 174]
  [190 178 173]
  ...
  [ 43  57  39]
  [ 37  37  27]
  [ 48  41  33]]

 ...

 [[ 60  65  76]
  [ 55  59  67]
  [ 54  60  63]
  ...
  [ 81  78 109]
  [ 87  76 115]
  [ 70  55  94]]

 [[ 63  57  80]
  [ 59  57  73]
  [ 57  59  68]
  ...
  [ 84  69 108]
  [ 93  67 107]
  [ 90  63 102]]

 [[ 73  64  67]
  [ 71  64  63]
  [ 60  58  60]
  ...
  [ 85  75 100]
  [ 90  68  95]
  [100  74 106]]]
[[[196 186 190]
  [203 185 187]
  [210 181 183]
  ...
  [ 42  46  51]
  [ 44  45  51]
  [ 47  44  48]]

 [[203 176 186]
  [205 176 182]
  [198 169 171]
  ...
  [ 50  46  53]
  [ 43  41  46]
  [ 49  48  54]]

 [[204 166 174]
  [206 170 177]
  [204 174 178]
  ...
  [ 46  47  48]
  [ 39  51  47]
  [ 40  56  47]]

 ...

 [[ 63  64  71]
  [ 62  60  74]
  [ 61  57  73]
  ..

[[[217 178 182]
  [206 165 172]
  [214 175 181]
  ...
  [ 44  38  57]
  [ 49  39  52]
  [ 48  38  41]]

 [[211 181 177]
  [196 169 167]
  [200 176 178]
  ...
  [ 52  52  62]
  [ 41  37  47]
  [ 46  40  44]]

 [[201 182 178]
  [193 178 172]
  [194 179 177]
  ...
  [ 51  55  56]
  [ 47  51  47]
  [ 44  48  38]]

 ...

 [[ 63  72  83]
  [ 57  59  69]
  [ 68  66  73]
  ...
  [ 83  66 110]
  [ 84  66 118]
  [ 80  59 112]]

 [[ 66  57  71]
  [ 64  57  71]
  [ 69  60  76]
  ...
  [ 85  66 112]
  [ 90  59 121]
  [ 92  52 121]]

 [[ 78  52  77]
  [ 80  56  78]
  [ 76  53  77]
  ...
  [ 95  67 111]
  [ 93  56 109]
  [100  59 116]]]
[[[208 177 182]
  [206 176 181]
  [210 176 185]
  ...
  [ 54  52  51]
  [ 55  51  49]
  [ 53  46  42]]

 [[204 177 187]
  [200 179 183]
  [191 177 177]
  ...
  [ 52  52  51]
  [ 43  43  41]
  [ 44  46  41]]

 [[204 179 183]
  [197 178 179]
  [190 178 178]
  ...
  [ 42  55  49]
  [ 38  52  46]
  [ 39  57  49]]

 ...

 [[ 60  70  64]
  [ 64  68  63]
  [ 65  62  61]
  ..

[[[199 177 191]
  [193 172 175]
  [206 183 184]
  ...
  [ 69  38  32]
  [ 75  40  31]
  [ 66  32  27]]

 [[200 184 178]
  [202 181 174]
  [204 179 176]
  ...
  [ 55  47  36]
  [ 54  44  31]
  [ 60  54  43]]

 [[201 177 173]
  [201 173 171]
  [202 172 171]
  ...
  [ 49  55  55]
  [ 45  48  47]
  [ 50  56  54]]

 ...

 [[ 67  65  61]
  [ 70  66  67]
  [ 73  60  75]
  ...
  [ 77  67 108]
  [ 82  69 116]
  [ 69  55 104]]

 [[ 67  58  61]
  [ 72  62  68]
  [ 66  53  70]
  ...
  [ 76  60 105]
  [ 83  63 116]
  [ 81  61 118]]

 [[ 68  57  75]
  [ 73  59  76]
  [ 62  49  64]
  ...
  [ 74  62 111]
  [ 79  63 116]
  [ 86  70 124]]]
[[[213 189 176]
  [210 184 176]
  [205 180 173]
  ...
  [ 75  36  46]
  [ 70  41  51]
  [ 56  30  53]]

 [[206 186 174]
  [199 177 164]
  [202 179 165]
  ...
  [ 45  39  37]
  [ 51  41  41]
  [ 54  43  46]]

 [[198 182 176]
  [195 174 172]
  [201 174 175]
  ...
  [ 42  53  51]
  [ 42  48  45]
  [ 47  51  44]]

 ...

 [[ 36  73  72]
  [ 43  67  72]
  [ 56  63  76]
  ..

[[[202 187 162]
  [204 185 169]
  [203 183 181]
  ...
  [ 50  33  50]
  [ 51  25  36]
  [ 67  31  34]]

 [[204 181 165]
  [200 177 168]
  [198 180 175]
  ...
  [ 50  51  47]
  [ 49  36  35]
  [ 58  31  33]]

 [[203 179 182]
  [194 174 172]
  [195 179 172]
  ...
  [ 47  47  44]
  [ 49  36  30]
  [ 59  42  33]]

 ...

 [[ 67  62  70]
  [ 65  61  71]
  [ 56  57  65]
  ...
  [ 79  70 102]
  [ 86  75 109]
  [ 72  62  93]]

 [[ 77  50  86]
  [ 68  53  83]
  [ 67  59  82]
  ...
  [ 80  78 102]
  [ 80  81 104]
  [ 67  70  91]]

 [[ 69  56  79]
  [ 69  57  80]
  [ 60  53  68]
  ...
  [ 76  73 105]
  [ 74  75  97]
  [ 74  77  92]]]
[[[210 182 185]
  [204 178 181]
  [195 171 177]
  ...
  [ 55  39  41]
  [ 50  45  44]
  [ 46  44  56]]

 [[194 167 167]
  [202 177 178]
  [200 174 176]
  ...
  [ 64  43  44]
  [ 52  41  35]
  [ 55  48  41]]

 [[199 174 168]
  [198 172 169]
  [202 174 175]
  ...
  [ 49  43  35]
  [ 50  41  36]
  [ 62  54  48]]

 ...

 [[ 60  58  46]
  [ 62  60  57]
  [ 59  56  67]
  ..

[[[206 184 185]
  [200 180 177]
  [195 178 170]
  ...
  [ 61  40  49]
  [ 58  42  43]
  [ 60  44  32]]

 [[203 183 182]
  [200 181 179]
  [199 181 173]
  ...
  [ 46  39  42]
  [ 54  43  36]
  [ 53  45  29]]

 [[193 181 176]
  [194 181 174]
  [193 180 172]
  ...
  [ 40  37  39]
  [ 41  37  26]
  [ 48  53  33]]

 ...

 [[ 60  66  66]
  [ 56  61  67]
  [ 54  58  68]
  ...
  [ 66  76 101]
  [ 77  78 102]
  [ 76  66  86]]

 [[ 57  59  54]
  [ 62  66  66]
  [ 58  71  77]
  ...
  [ 71  72  98]
  [ 77  72  95]
  [ 79  72  93]]

 [[ 72  53  84]
  [ 65  53  77]
  [ 55  56  70]
  ...
  [ 72  74 106]
  [ 73  71  96]
  [ 75  73  89]]]
[[[217 181 168]
  [207 175 162]
  [209 183 172]
  ...
  [ 54  42  47]
  [ 62  40  57]
  [ 61  28  61]]

 [[192 172 173]
  [197 175 172]
  [202 180 173]
  ...
  [ 48  48  49]
  [ 56  40  53]
  [ 59  29  52]]

 [[180 181 174]
  [181 176 169]
  [195 183 177]
  ...
  [ 44  52  48]
  [ 44  51  47]
  [ 37  41  40]]

 ...

 [[ 60  55  68]
  [ 55  53  70]
  [ 54  60  76]
  ..

[[[210 185 160]
  [208 176 161]
  [206 174 172]
  ...
  [ 64  36  53]
  [ 56  23  47]
  [ 61  28  57]]

 [[204 181 170]
  [197 174 168]
  [198 177 180]
  ...
  [ 46  41  42]
  [ 49  37  39]
  [ 58  42  46]]

 [[201 175 180]
  [199 174 179]
  [200 177 186]
  ...
  [ 48  48  47]
  [ 46  38  41]
  [ 52  45  47]]

 ...

 [[ 64  61  62]
  [ 59  56  59]
  [ 55  55  63]
  ...
  [ 81  75 108]
  [ 84  75 106]
  [ 74  68  92]]

 [[ 54  63  64]
  [ 57  68  71]
  [ 54  67  77]
  ...
  [ 65  63  98]
  [ 76  68 103]
  [ 71  62  93]]

 [[ 51  73  89]
  [ 48  64  82]
  [ 52  61  83]
  ...
  [ 66  68 108]
  [ 74  65 102]
  [ 79  67 102]]]
[[[212 175 176]
  [210 175 175]
  [205 175 176]
  ...
  [ 48  44  34]
  [ 54  52  39]
  [ 47  50  44]]

 [[205 183 165]
  [207 180 167]
  [207 179 175]
  ...
  [ 46  52  43]
  [ 48  48  35]
  [ 51  45  34]]

 [[192 184 169]
  [191 178 169]
  [195 177 175]
  ...
  [ 48  52  41]
  [ 43  47  37]
  [ 45  48  39]]

 ...

 [[ 53  63  84]
  [ 56  65  81]
  [ 51  63  75]
  ..